// frontend-React/src/pages/UserProfile/UserProfile.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { UserProfileDetails } from '../../types/user/userProfileDetails';
import ReplyList from '../../components/Reply/ReplyList/ReplyList';
import TweetList from '../../components/Tweet/TweetList/TweetList';
import UpdateProfile from '../../components/User/UpdateProfile/UpdateProfile';
import { HttpConfig } from '../../config/http-config';
import styles from './UserProfile.module.css';
import { follow, getUserProfile, unfollow } from '../../services/userProfileService';
import { useSelector } from 'react-redux';
import { selectUserId } from '../../store/slices/authSlice';
import backIcon from '../../assets/icons/back-arrow.svg';


const UserProfile: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const currentUserId = useSelector(selectUserId);

  const [profile, setProfile] = useState<UserProfileDetails | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'tweets' | 'replies'>('tweets');
  const [showSetupProfileModal, setShowSetupProfileModal] = useState(false);
  const [listKey, setListKey] = useState<string>(`user-${id}-tweets`); // Key for TweetList/ReplyList

  const profileUserId = Number(id);

  const fetchProfile = useCallback(async () => {
    if (!profileUserId) return;
    setIsLoading(true);
    setError(null);
    try {
      const data = await getUserProfile(profileUserId); 
      setProfile(data);
    } catch (err) {
      console.error("Failed to fetch profile:", err);
      setError('Failed to load profile.');
    } finally {
      setIsLoading(false);
    }
  }, [profileUserId]); 

  useEffect(() => {
    fetchProfile();
    // Reset tab to tweets when profile changes
    setActiveTab('tweets');
    setListKey(`user-${id}-tweets`); // Update list key when ID changes
  }, [fetchProfile, id]); // Depend on id from useParams as well

  const handleToggleFollow = async () => {
    if (!profile || currentUserId === null || currentUserId === profileUserId) return;

    const wasFollowing = profile.isFollowing;
    // Optimistic update
    setProfile(prev => prev ? { 
        ...prev, 
        isFollowing: !wasFollowing,
        followersCount: wasFollowing ? prev.followersCount - 1 : prev.followersCount + 1
    } : null);

    try {
      if (wasFollowing) {
        await unfollow(profileUserId);
      } else {
        await follow(profileUserId);
      }
      // Optional: Refetch profile for consistency, though optimistic update might suffice
      // fetchProfile(); 
    } catch (err) {
      console.error('Failed to toggle follow:', err);
      // Revert optimistic update on error
      setProfile(prev => prev ? { 
        ...prev, 
        isFollowing: wasFollowing,
        followersCount: wasFollowing ? prev.followersCount + 1 : prev.followersCount - 1 
       } : null);
      alert('Could not update follow status.');
    }
  };

  const handleProfileUpdated = () => {
     setShowSetupProfileModal(false);
     fetchProfile(); // Refetch profile data after update
  }

  const switchTab = (tab: 'tweets' | 'replies') => {
      setActiveTab(tab);
      setListKey(`user-${profileUserId}-${tab}-${Date.now()}`); // Force remount/refresh of list
  }

  const getFullImageUrl = (profilePicturePath: string | null | undefined) => {
      if (!profilePicturePath) {
          return '/icons/default-avatar.png'; 
      }
      return `${HttpConfig.baseUrl}${profilePicturePath}`;
  };

  const goBack = () => {
    navigate('/home');
  };

  if (isLoading) {
    return <div>Loading profile...</div>;
  }

  if (error) {
    return <div>{error}</div>;
  }

  if (!profile) {
    return <div>Profile not found.</div>;
  }

  return (
    <div className={styles.profileContainer}>
      <div className={styles.headerBar}>
        <button onClick={goBack} className={styles.backButton}>
           <img src={backIcon} alt="Go Back" className={styles.arrowIcon} />
           <span className={styles.arrowIcon}></span>
        </button>
        <span className={styles.headerNickname}>{profile.nickname}</span>
      </div>

      {showSetupProfileModal && (
          <div className="overlay" onClick={() => setShowSetupProfileModal(false)}>
              <div className={`modal ${styles.updateProfileModal}`} onClick={e => e.stopPropagation()}> 
                 <button className={`close-btn ${styles.customCloseBtn}`} onClick={() => setShowSetupProfileModal(false)}>&times;</button>
                 <UpdateProfile onProfileUpdated={handleProfileUpdated} />
              </div>
           </div>
      )}

      <div className={styles.profileHeader}>
        <div className={styles.headerTopSection}>
            <img 
                src={getFullImageUrl(profile.profilePicture)}
                alt={`${profile.nickname}'s profile picture`} 
                className={styles.avatarImg}
            />
           {currentUserId === profileUserId ? (
             <button className={styles.setupProfile} onClick={() => setShowSetupProfileModal(true)}>
               Set up profile
             </button>
           ) : (
             <button 
                onClick={handleToggleFollow} 
                className={`${styles.followBtn} ${profile.isFollowing ? styles.following : ''}`}
             >
               {profile.isFollowing ? 'Unfollow' : 'Follow'}
             </button>
           )}
        </div>

        <div className={styles.userInfoSection}>
            <h2 className={styles.userNickname}>{profile.nickname}</h2>
            
            <p className={styles.bioText}>{profile.bio || ''}</p>
            <div className={styles.followCounts}>
                <span className={styles.countItem}><b>{profile.followingCount}</b> Following</span>
                <span className={styles.countItem}><b>{profile.followersCount}</b> Followers</span>
             </div>
        </div>
        
      </div>

      <div className={styles.profileTabs}>
        <button 
            onClick={() => switchTab('tweets')} 
            className={`${styles.tabButton} ${activeTab === 'tweets' ? styles.active : ''}`}
        >
            Posts
        </button>
        <button 
            onClick={() => switchTab('replies')} 
            className={`${styles.tabButton} ${activeTab === 'replies' ? styles.active : ''}`}
        >
            Replies
        </button>
      </div>

      <div className={styles.profileContent}>
        {activeTab === 'tweets' && (
          <TweetList 
            userId={profileUserId} 
            fetchType='user'
            listKey={listKey} // Use state key
          />
        )}
        {activeTab === 'replies' && (
          <ReplyList 
            userId={profileUserId} 
            onOpenReplyPopup={() => { /* Define or pass reply popup logic if needed here */ }}
            listKey={listKey} // Use state key
          />
        )}
      </div>
    </div>
  );
};

export default UserProfile;

// frontend/src/app/user/user-profile/user-profile.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { UserProfileDetails } from '../../model/user/userProfileDetails';
import { ReplyListComponent } from '../../reply/reply-list/reply-list.component';
import { TweetListComponent } from '../../tweet/tweet-list/tweet-list.component';
import { UpdateProfileComponent } from '../update-profile/update-profile.component';
import { HttpConfig } from '../../config/http-config';
import { UserProfileService } from '../../model/user/userProfileService';
import { AuthService } from '../../model/authentication/authService';

@Component({
  selector: 'app-user-profile',
  imports: [RouterModule, CommonModule, TweetListComponent, ReplyListComponent, UpdateProfileComponent],
  templateUrl: './user-profile.component.html',
  styleUrl: './user-profile.component.css'
})
export class UserProfileComponent implements OnInit {
  profile: UserProfileDetails | null = null;
  isLoading = true;
  error: string | null = null;
  activeTab: 'tweets' | 'replies' = 'tweets';
  showSetupProfileModal = false;
  listKey: string = '';
  profileUserId!: number;
  currentUserId: number | null = null;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private userProfileService: UserProfileService,
    private authService: AuthService
  ) { }

  ngOnInit(): void {
    this.authService.userId$.subscribe(id => this.currentUserId = id);
    this.route.paramMap.subscribe(params => {
      const idParam = params.get('id');
      if (idParam) {
        this.profileUserId = Number(idParam);
        this.fetchProfile();
        this.activeTab = 'tweets';
        this.listKey = `user-${this.profileUserId}-tweets-${Date.now()}`;
      } else {
        this.error = 'User ID not provided.';
        this.isLoading = false;
      }
    });
  }

  fetchProfile(): void {
    if (!this.profileUserId) return;
    this.isLoading = true;
    this.error = null;
    this.userProfileService.getUserProfile(this.profileUserId).subscribe({
      next: data => {
        this.profile = data;
        this.isLoading = false;
      },
      error: err => {
        console.error("Failed to fetch profile:", err);
        this.error = 'Failed to load profile.';
        this.isLoading = false;
      }
    });
  }

  toggleFollow(): void {
    if (!this.profile || this.currentUserId === null || this.currentUserId === this.profileUserId) return;

    const wasFollowing = this.profile.isFollowing;
    // Optimistic update is tricky without knowing the new counts from backend immediately
    // For simplicity, we'll refetch or rely on backend to return updated profile if that's the API design
    const action = wasFollowing ? this.userProfileService.unfollow(this.profileUserId) : this.userProfileService.follow(this.profileUserId);
    
    action.subscribe({
        next: () => this.fetchProfile(), // Refetch to get updated state including counts
        error: (err) => {
            console.error('Failed to toggle follow:', err);
            alert('Could not update follow status.');
            // Optionally revert optimistic UI changes if any were made
        }
    });
  }

  handleProfileUpdated(): void {
     this.showSetupProfileModal = false;
     this.fetchProfile();
  }

  openSetupProfileModal(): void {
    this.showSetupProfileModal = true;
  }

  closeSetupProfileModal(): void {
    this.showSetupProfileModal = false;
  }

  switchTab(tab: 'tweets' | 'replies'): void {
      this.activeTab = tab;
      this.listKey = `user-${this.profileUserId}-${tab}-${Date.now()}`;
  }

  getFullImageUrl(profilePicturePath: string | null | undefined): string {
      if (!profilePicturePath) {
          return '/icons/default-avatar.png'; 
      }
      return `${HttpConfig.baseUrl}${profilePicturePath}`;
  };

  goBack(): void {
    this.router.navigate(['/home']);
  }
  
  noopReplyPopup(event: any): void{
    // Placeholder if UserProfile doesn't directly handle opening reply popups from its lists
  }
}

<div class="profileContainer">
  <div class="headerBar">
    <button (click)="goBack()" class="backButton">
        <img src="/icons/back-arrow.svg" alt="Go Back" class="arrowIcon" />
    </button>
    @if (profile) {
      <span class="headerNickname">{{ profile.nickname }}</span>
    }
  </div>

  @if (isLoading) {
    <div>Loading profile...</div>
  }
  @if (error) {
    <div>{{ error }}</div>
  }
  @if (!isLoading && !profile) {
    <div>Profile not found.</div>
  }

  @if (profile) {
    @if (showSetupProfileModal) {
      <div class="overlay" (click)="closeSetupProfileModal()">
          <div class="modal updateProfileModal" (click)="$event.stopPropagation()">
             <button class="close-btn customCloseBtn" (click)="closeSetupProfileModal()">&times;</button>
             <app-update-profile (profileUpdated)="handleProfileUpdated()" (cancelUpdate)="closeSetupProfileModal()"></app-update-profile>
          </div>
       </div>
    }

    <div class="profileHeader">
      <div class="headerTopSection">
          <img [src]="getFullImageUrl(profile.profilePicture)" [alt]="profile.nickname + '\'s profile picture'" class="avatarImg">
         @if (currentUserId === profileUserId) {
           <button class="setupProfile" (click)="openSetupProfileModal()">
             Set up profile
           </button>
         } @else {
           <button (click)="toggleFollow()" class="followBtn {{ profile.isFollowing ? 'following' : '' }}">
             {{ profile.isFollowing ? 'Unfollow' : 'Follow' }}
           </button>
         }
      </div>

      <div class="userInfoSection">
          <h2 class="userNickname">{{ profile.nickname }}</h2>
          <p class="bioText">{{ profile.bio || '' }}</p>
          <div class="followCounts">
              <span class="countItem"><b>{{ profile.followingCount }}</b> Following</span>
              <span class="countItem"><b>{{ profile.followersCount }}</b> Followers</span>
           </div>
      </div>
    </div>

    <div class="profileTabs">
      <button (click)="switchTab('tweets')" class="tabButton {{ activeTab === 'tweets' ? 'active' : '' }}">
          Posts
      </button>
      <button (click)="switchTab('replies')" class="tabButton {{ activeTab === 'replies' ? 'active' : '' }}">
          Replies
      </button>
    </div>

    <div class="profileContent">
      @if (activeTab === 'tweets') {
        <app-tweet-list [userId]="profileUserId" fetchType="user" [listKey]="listKey"></app-tweet-list>
      }
      @if (activeTab === 'replies') {
        <app-reply-list [userId]="profileUserId" (openReplyPopup)="noopReplyPopup($event)" [listKey]="listKey"></app-reply-list>
      }
    </div>
  }
</div>
