// frontend-React/src/components/Tweet/SingleTweet/SingleTweet.tsx
import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { DisplayTweetDetails } from '../../../types/tweet/displayTweetDetails';
import { HttpConfig } from '../../../config/http-config';
import styles from './SingleTweet.module.css';
import { addBookmarkToTweet, addLikeToTweet, removeBookmarkFromTweet, removeLikeFromTweet } from '../../../services/tweetService';
import { useSelector } from 'react-redux';
import { selectUserId } from '../../../store/slices/authSlice';
import replyIcon from '../../../assets/icons/tweet-buttons/reply.svg';
import likeIcon from '../../../assets/icons/tweet-buttons/like.svg';
import bookmarkIcon from '../../../assets/icons/tweet-buttons/bookmark.svg';

interface SingleTweetProps {
  tweet: DisplayTweetDetails;
  isDetailView?: boolean;
}

const SingleTweet: React.FC<SingleTweetProps> = ({ tweet, isDetailView = false }) => {
  const userId = useSelector(selectUserId);
  const navigate = useNavigate();
  const [localTweet, setLocalTweet] = useState<DisplayTweetDetails>(tweet);

  useEffect(() => {
    setLocalTweet(tweet);
  }, [tweet]);

  const handleLikeToggle = async (event: React.MouseEvent<HTMLButtonElement>) => {
    event.stopPropagation();
    if (!userId) return;

    const currentLikeId = localTweet.likeId;
    const currentlyLiked = localTweet.liked;
    const currentLikeCount = localTweet.likeCount;


    setLocalTweet(prev => ({
      ...prev,
      liked: !currentlyLiked,
      likeCount: currentlyLiked ? currentLikeCount - 1 : currentLikeCount + 1,
      likeId: currentlyLiked ? undefined : -1
    }));

    try {
      if (!currentlyLiked) {
        const likeData = { userId: userId, tweetId: localTweet.id };
        const result = await addLikeToTweet(likeData);

        setLocalTweet(prev => ({ ...prev, likeCount: result.likeCount, likeId: result.likeId, liked: true }));
      } else if (currentLikeId) {
        const result = await removeLikeFromTweet(currentLikeId);

        setLocalTweet(prev => ({ ...prev, likeCount: result.likeCount, likeId: undefined, liked: false }));
      }
    } catch (error) {
      console.error("Failed to toggle like:", error);

      setLocalTweet(prev => ({ ...prev, liked: currentlyLiked, likeCount: currentLikeCount, likeId: currentLikeId }));
      alert("Could not update like status.");
    }
  };

  const handleBookmarkToggle = async (event: React.MouseEvent<HTMLButtonElement>) => {
    event.stopPropagation();
    if (!userId) return;

    const currentBookmarkId = localTweet.bookmarkId;
    const currentlyBookmarked = localTweet.bookmarked;
    const currentBookmarkCount = localTweet.bookmarkCount;


    setLocalTweet(prev => ({
      ...prev,
      bookmarked: !currentlyBookmarked,
      bookmarkCount: currentlyBookmarked ? currentBookmarkCount - 1 : currentBookmarkCount + 1,
      bookmarkId: currentlyBookmarked ? undefined : -1
    }));

    try {
      const currentDate = new Date();
      const creationDate = currentDate.toISOString().split('T')[0];
      const creationTime = currentDate.toISOString().split('T')[1].split('.')[0];

      if (!currentlyBookmarked) {
        const bookmarkData = {
          userId: userId,
          tweetId: localTweet.id,
          creationDate: creationDate,
          creationTime: creationTime
        };
        const result = await addBookmarkToTweet(bookmarkData);
        setLocalTweet(prev => ({
          ...prev,
          bookmarkCount: result.bookmarkCount,
          bookmarkId: result.bookmarkId,
          bookmarked: true
        }));
      } else if (currentBookmarkId !== undefined) {
        const result = await removeBookmarkFromTweet(currentBookmarkId);
        setLocalTweet(prev => ({
          ...prev,
          bookmarkCount: result.bookmarkCount,
          bookmarkId: undefined,
          bookmarked: false
        }));
      }
    } catch (error) {
      console.error("Failed to toggle bookmark:", error);
      setLocalTweet(prev => ({
        ...prev,
        bookmarked: currentlyBookmarked,
        bookmarkCount: currentBookmarkCount,
        bookmarkId: currentBookmarkId
      }));
      alert("Could not update bookmark status.");
    }
  };

  const handleReplyClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    event.stopPropagation();

    if (!isDetailView) {
      navigate(`/tweet/${localTweet.id}`);
    }
  }

  const navigateToTweet = () => {
    if (!isDetailView) {
      navigate(`/tweet/${localTweet.id}`);
    }
  };

  const getFullImageUrl = (profilePicturePath: string | null | undefined) => {
    if (!profilePicturePath) {
      return '/icons/default-avatar.png';
    }
    return `${HttpConfig.baseUrl}${profilePicturePath}`;
  };

  return (
    <div className={styles.tweetContainer} onClick={navigateToTweet} role="article" tabIndex={0}>
      <div className={styles.tweetHeader}>
        <Link
          to={`/profile/${localTweet.userId}`}
          onClick={(e) => e.stopPropagation()}
          className={styles.profilePicLink}
        >
          <img
            className={styles.profilePicture}
            src={getFullImageUrl(localTweet.userProfilePicture)}
            alt={`Profile picture of ${localTweet.userNickname}`}
          />
        </Link>
        <div className={styles.userInfoContainer}>
          <div className={styles.userInfo}>
            <Link
              to={`/profile/${localTweet.userId}`}
              className={styles.nicknameLink}
              onClick={(e) => e.stopPropagation()}
            >
              <h3 className={styles.nickname}>{localTweet.userNickname}</h3>
            </Link>

            <p className={styles.time}>&middot; {localTweet.creationDate} {isDetailView ? ` \u00b7 ${localTweet.creationTime}` : ''}</p>
          </div>
          <div className={styles.tweetContent}>
            <p>{localTweet.content}</p>
          </div>
        </div>
      </div>

      <div className={styles.actions}>
        <div className={styles.interactionButtons}>
          <button className={`${styles.interactionButton} ${styles.likeButton} ${localTweet.liked ? styles.active : ''}`} onClick={handleLikeToggle} aria-label={localTweet.liked ? 'Unlike' : 'Like'} aria-pressed={localTweet.liked}>
            <img className={styles.interactionIcon} src={likeIcon} alt="Like" />
            <span className={styles.interactionCount}>{localTweet.likeCount ?? 0}</span>
          </button>

          <button className={`${styles.interactionButton} ${styles.replyButton}`} onClick={handleReplyClick} aria-label="Reply">
            <img className={styles.interactionIcon} src={replyIcon} alt="Reply" />
            <span className={styles.interactionCount}>{localTweet.replyCount ?? 0}</span>
          </button>

          <button className={`${styles.interactionButton} ${styles.bookmarkButton} ${localTweet.bookmarked ? styles.active : ''}`} onClick={handleBookmarkToggle} aria-label={localTweet.bookmarked ? 'Remove bookmark' : 'Bookmark'} aria-pressed={localTweet.bookmarked}>
            <img className={styles.interactionIcon} src={bookmarkIcon} alt="Bookmark" />
            <span className={styles.interactionCount}>{localTweet.bookmarkCount ?? 0}</span>
          </button>
        </div>
      </div>
    </div>
  );
};

export default SingleTweet;

// frontend/src/app/single-tweet/single-tweet.component.ts
import { ChangeDetectorRef, Component, Input } from '@angular/core';
import { DisplayTweetDetails } from '../model/tweet/displayTweetDetails';
import { LikeTweetDetails } from '../model/tweet/likeTweetDetails';
import { TweetService } from '../model/tweet/tweetService';
import { BookmarkDetails } from '../model/tweet/bookmarkDetails';
import { Router } from '@angular/router';

@Component({
  selector: 'app-single-tweet',
  imports: [],
  templateUrl: './single-tweet.component.html',
  styleUrl: './single-tweet.component.css'
})
export class SingleTweetComponent {
  likeDetails!: LikeTweetDetails;
  bookmarkDetails!: BookmarkDetails;

  @Input({
    required: true
  })
  tweet!: DisplayTweetDetails;
  @Input({
    required: true
  })
  userId!: number;

  constructor(
    private tweetService: TweetService,
    private cdr: ChangeDetectorRef,
    private router: Router
  ) { }

  // Toggle like
  toggleLike() {
    this.likeDetails = {
      id: 0,
      userId: this.userId,
      tweetId: this.tweet.id
    };

    if (!this.tweet.liked) {
      this.tweetService
        .addLikeToTweet(this.likeDetails)
        .subscribe({
          next: r => {
            this.tweet.liked = true;
            this.tweet.likeCount = r.likeCount;
            this.tweet.likeId = r.likeId;
            this.cdr.detectChanges();
          },
          error: err => console.log(err)
        });
    } else {
      this.tweetService
        .removeLikeFromTweet(this.tweet.likeId)
        .subscribe({
          next: r => {
            this.tweet.liked = false;
            this.tweet.likeCount = r.likeCount;
            this.tweet.likeId = undefined;
            this.cdr.detectChanges();
          },
          error: err => console.log(err)
        });
    }
  }

  // Toggle bookmark
  toggleBookmark() {
    this.bookmarkDetails = {
      id: 0,
      userId: this.userId,
      tweetId: this.tweet.id,
      creationDate: new Date().toISOString().split('T')[0],
      creationTime: new Date().toLocaleTimeString("it-IT", { hour: "2-digit", minute: "2-digit" })
    };

    if (!this.tweet.bookmarked) {
      this.tweetService
        .addBookmarkToTweet(this.bookmarkDetails)
        .subscribe({
          next: r => {
            this.tweet.bookmarked = true;
            this.tweet.bookmarkCount = r.bookmarkCount;
            this.tweet.bookmarkId = r.bookmarkId;
            this.cdr.detectChanges();
          },
          error: err => console.log(err)
        });
    } else {
      this.tweetService
        .removeBookmarkFromTweet(this.tweet.bookmarkId)
        .subscribe({
          next: r => {
            this.tweet.bookmarked = false;
            this.tweet.bookmarkCount = r.bookmarkCount;
            this.tweet.bookmarkId = undefined;
            this.cdr.detectChanges();
          },
          error: err => console.log(err)
        });
    }
  }

  // Open a tweet
  openTweet(tweetId: number) {
    this.router.navigate(['/tweet', tweetId]);
  }
}

<div class="tweet" (click)="openTweet(tweet.id)">
    <div class="post-header">
        <div class="user-info">
            <h3>{{ tweet.userNickname }}</h3>
            <p class="time">{{ tweet.creationDate }} · {{ tweet.creationTime }}</p>
        </div>
    </div>
    <div class="post-content">
        <p>{{ tweet.content }}</p>
    </div>
    <div class="actions">
        <div class="interaction-buttons">
            <button class="interaction-button like-button" [class.active]="tweet.liked" 
                (click)="toggleLike(); $event.stopPropagation()">
                <img class="interaction-icon" src="icons/tweet-buttons/like.svg" alt="Like">
                <span class="interaction-count">{{ tweet.likeCount }}</span>
            </button>
            <button class="interaction-button reply-button">
                <img class="interaction-icon" src="icons/tweet-buttons/reply.svg" alt="Reply">
                <span class="interaction-count">{{ tweet.replyCount }}</span>
            </button>
            <button class="interaction-button bookmark-button" [class.active]="tweet.bookmarked"
                (click)="toggleBookmark(); $event.stopPropagation()">
                <img class="interaction-icon" src="icons/tweet-buttons/bookmark.svg" alt="Bookmark">
                <span class="interaction-count">{{ tweet.bookmarkCount }}</span>
            </button>
        </div>
    </div>
</div>
