// frontend/src/app/user/update-profile/update-profile.component.ts
import { Component, OnInit, Output, EventEmitter, Input } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import Compressor from 'compressorjs';
import { UserProfileService } from '../../model/user/userProfileService';
import { UserService } from '../../model/user/userService'; 
import { AuthService } from '../../model/authentication/authService'; 
import { HttpConfig } from '../../config/http-config';
import { UserProfileDetails } from '../../model/user/userProfileDetails';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-update-profile',
  imports: [ReactiveFormsModule, CommonModule],
  templateUrl: './update-profile.component.html',
  styleUrls: ['./update-profile.component.css']
})
export class UpdateProfileComponent implements OnInit {
  @Output() profileUpdated = new EventEmitter<void>();
  @Output() cancelUpdate = new EventEmitter<void>();

  profileForm!: FormGroup;
  avatarPreview: string | ArrayBuffer | null = null;
  selectedAvatarFile: File | null = null;
  isProcessing = false;
  currentUserId: number | null = null;
  currentUserProfile: UserProfileDetails | null = null;

  constructor(
    private fb: FormBuilder,
    private userProfileService: UserProfileService,
    private userService: UserService, 
    private authService: AuthService 
  ) {}

  ngOnInit(): void {
    this.authService.userId$.subscribe(id => {
      this.currentUserId = id;
      if (this.currentUserId) {
        this.loadProfileDetails(this.currentUserId);
      }
    });

    this.profileForm = this.fb.group({
      bio: ['', [Validators.maxLength(255)]],
      avatar: [null]
    });
  }

  loadProfileDetails(userId: number): void {
    this.userProfileService.getUserProfile(userId).subscribe({
        next: (profileData) => {
            this.currentUserProfile = profileData;
            this.profileForm.patchValue({ bio: profileData.bio || '' });
            if (profileData.profilePicture) {
                this.avatarPreview = `${HttpConfig.baseUrl}${profileData.profilePicture}`;
            } else {
                this.avatarPreview = null;
            }
        },
        error: (err) => console.error('Failed to load profile details', err)
    });
  }

  onFileChange(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (input?.files?.[0]) {
      const originalFile = input.files[0];
      if (!originalFile.type.startsWith('image/')) {
        alert('Please select an image file.');
        return;
      }
      new Compressor(originalFile, {
        quality: 0.6, maxWidth: 800, maxHeight: 800,
        success: (compressedResult) => {
          this.selectedAvatarFile = new File([compressedResult], originalFile.name, { type: compressedResult.type || originalFile.type });
          const reader = new FileReader();
          reader.onloadend = () => { this.avatarPreview = reader.result as string; };
          reader.readAsDataURL(this.selectedAvatarFile);
          this.profileForm.get('avatar')?.markAsDirty(); // Mark as dirty for form state
        },
        error: (err) => {
          console.error('Compression error:', err.message);
          alert('Could not process image. Please try another one.');
          this.avatarPreview = this.currentUserProfile?.profilePicture ? `${HttpConfig.baseUrl}${this.currentUserProfile.profilePicture}` : null;
          this.selectedAvatarFile = null;
        },
      });
    } else {
        this.avatarPreview = this.currentUserProfile?.profilePicture ? `${HttpConfig.baseUrl}${this.currentUserProfile.profilePicture}` : null;
        this.selectedAvatarFile = null;
        this.profileForm.get('avatar')?.setValue(null);
    }
  }

  onSubmit(): void {
    if (this.profileForm.invalid || !this.currentUserId) return;
    if (!this.profileForm.dirty && !this.selectedAvatarFile) {
        this.profileUpdated.emit(); // No changes, just close
        return;
    }

    this.isProcessing = true;
    const formData = new FormData();
    formData.append('bio', this.profileForm.get('bio')?.value || '');
    if (this.selectedAvatarFile) {
      formData.append('avatar', this.selectedAvatarFile);
    }

    this.userProfileService.updateProfile(formData, this.currentUserId).subscribe({
      next: () => {
        if (this.currentUserId) {
            this.userService.fetchUserDetails(this.currentUserId).subscribe(); // Refresh global user details
        }
        this.profileUpdated.emit();
        this.isProcessing = false;
      },
      error: (err) => {
        console.error('Failed to update profile:', err);
        alert('Failed to update profile. Please try again.');
        this.isProcessing = false;
      }
    });
  }
}
<div class="profileUpdateContainer">
    <form (ngSubmit)="onSubmit()" [formGroup]="profileForm">
      <div class="avatarContainer">
        <p class="chooseAvatarText">Pick a profile picture</p>
        <label for="avatarFile" class="avatarLabel">
          @if (avatarPreview) {
            <img [src]="avatarPreview" alt="Avatar Preview" class="avatarPreview" />
          } @else {
            <img src="/icons/default-avatar.png" alt="Default Avatar" class="avatarPreview" />
          }
        </label>
        <input type="file" id="avatarFile" accept="image/*" (change)="onFileChange($event)" class="fileInput" #avatarFileInput/>
      </div>
  
      <div class="bioContainer">
        <label for="bio">Describe yourself</label>
        <textarea id="bio" formControlName="bio" rows="4" 
                  placeholder="What makes you special? Don't think too hard, just have fun with it."
                  [class.inputError]="profileForm.get('bio')?.invalid && profileForm.get('bio')?.touched">
        </textarea>
        @if (profileForm.get('bio')?.invalid && profileForm.get('bio')?.touched && profileForm.get('bio')?.errors?.['maxlength']) {
            <span class="validationMessage">Bio cannot exceed 255 characters</span>
        }
      </div>
  
      <div class="formActions">
        <button type="submit" class="submitButton" [disabled]="!profileForm.valid || isProcessing || (!profileForm.dirty && !selectedAvatarFile)">
            {{ isProcessing ? 'Saving...' : 'Save Changes' }}
        </button>
        <button type="button" (click)="cancelUpdate.emit()" class="cancelButton">Cancel</button>
      </div>
    </form>
  </div>

// frontend-React/src/components/User/UpdateProfile/UpdateProfile.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { useForm, SubmitHandler, Controller } from 'react-hook-form';
import Compressor from 'compressorjs';
import { UpdateProfilePayload } from '../../../types/user/UpdateProfilePayload';
import { updateProfile, getUserProfile } from '../../../services/userProfileService'; // Import getUserProfile
import { HttpConfig } from '../../../config/http-config';
import styles from './UpdateProfile.module.css';
import { UserProfileDetails } from '../../../types/user/userProfileDetails';
import { useSelector, useDispatch } from 'react-redux';
import { selectUserId } from '../../../store/slices/authSlice';
import { fetchUserDetails } from '../../../store/slices/userSlice';
import { AppDispatch } from '../../../store/store';

interface UpdateProfileProps {
  onProfileUpdated: () => void;
}

const UpdateProfile: React.FC<UpdateProfileProps> = ({ onProfileUpdated }) => {
  const userId = useSelector(selectUserId);
  const dispatch = useDispatch<AppDispatch>();
  const [userProfileDetails, setUserProfileDetails] = useState<UserProfileDetails | null>(null);
  const [isLoadingProfile, setIsLoadingProfile] = useState(false);

  const {
    register,
    handleSubmit,
    control,
    setValue,
    reset,
    formState: { errors, isDirty, isValid }
  } = useForm<UpdateProfilePayload>({
    mode: 'onChange',
    defaultValues: {
      bio: '',
      avatar: null
    }
  });

  const [avatarPreview, setAvatarPreview] = useState<string | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);

  // Fetch current profile details to populate the form
  const fetchCurrentProfile = useCallback(async () => {
    if (!userId) return;
    setIsLoadingProfile(true);
    try {
      const profileData = await getUserProfile(userId);
      setUserProfileDetails(profileData);
      // Reset form with fetched data
      reset({
        bio: profileData.bio || '',
        avatar: null // Don't pre-fill file input
      });
      if (profileData.profilePicture) {
        setAvatarPreview(`${HttpConfig.baseUrl}${profileData.profilePicture}`);
      } else {
        setAvatarPreview(null); // Ensure preview is cleared if no picture
      }
    } catch (error) {
      console.error('Failed to fetch profile details:', error);
    } finally {
      setIsLoadingProfile(false);
    }
  }, [userId, reset]);

  useEffect(() => {
    fetchCurrentProfile();
  }, [fetchCurrentProfile]);

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) {
      // If user cancels file selection, revert to original or clear preview if desired
      // Revert preview to original fetched profile picture
      setAvatarPreview(userProfileDetails?.profilePicture ? `${HttpConfig.baseUrl}${userProfileDetails.profilePicture}` : null);
      setValue('avatar', null, { shouldDirty: true }); // Mark as dirty if they clear it
      return;
    }

    if (!file.type.startsWith('image/')) {
      alert('Please select an image file.');
      return;
    }

    new Compressor(file, {
      quality: 0.6,
      maxWidth: 800,
      maxHeight: 800,
      success: (compressedResult) => {
        const compressedFile = compressedResult as File;
        const reader = new FileReader();
        reader.onloadend = () => {
          setAvatarPreview(reader.result as string);
        };
        reader.readAsDataURL(compressedFile);
        setValue('avatar', compressedFile, { shouldDirty: true, shouldValidate: true });
      },
      error: (err) => {
        console.error('Compression error:', err.message);
        alert('Could not process image. Please try another one.');
      },
    });
  };

  const onSubmit: SubmitHandler<UpdateProfilePayload> = async (data) => {
    if (!userId) {
      console.error('User ID not found');
      return;
    }

    const avatarChanged = !!data.avatar; // True if a new file is selected

    if (!isDirty && !avatarChanged) { // Use isDirty for bio, explicit check for avatar
        // console.log('No changes detected.');
        onProfileUpdated(); // Close modal even if no changes
        return;
    }

    setIsProcessing(true);
    const formData = new FormData();

    // Only append fields that are part of the change
    // Backend should handle null/empty bio correctly if needed
    formData.append('bio', data.bio || '');

    if (avatarChanged) {
      formData.append('avatar', data.avatar as Blob);
    }

    try {
      await updateProfile(formData, userId);
      // Refresh user details in the Redux store after successful update
      dispatch(fetchUserDetails(userId));
      onProfileUpdated(); // Callback to close modal/refresh profile page
    } catch (error) {
      console.error('Failed to update profile:', error);
      alert('Failed to update profile. Please try again.');
    } finally {
      setIsProcessing(false);
    }
  };

  if (isLoadingProfile) {
    return <div>Loading profile data...</div>; // Or a spinner
  }

  return (
    <div className={styles.profileUpdateContainer}>
      <form onSubmit={handleSubmit(onSubmit)}>
        <div className={styles.avatarContainer}>
          <p className={styles.chooseAvatarText}>Pick a profile picture</p>
          <label htmlFor="avatar" className={styles.avatarLabel}>
            {avatarPreview ? (
              <img src={avatarPreview} alt="Avatar Preview" className={styles.avatarPreview} />
            ) : (
              // Better placeholder or use a default avatar icon
              <img src='/icons/default-avatar.png' alt="Default Avatar" className={styles.avatarPreview} />
            )}
          </label>
          <Controller
            name="avatar"
            control={control}
            render={() => (
              <input
                type="file"
                id="avatar"
                accept="image/*"
                onChange={handleFileChange}
                className={styles.fileInput}
              />
            )}
          />
        </div>

        <div className={styles.bioContainer}>
          <label htmlFor="bio">Describe yourself</label>
          <textarea
            id="bio"
            {...register('bio', {
              maxLength: { value: 500, message: 'Bio cannot exceed 500 characters' }
            })}
            rows={4}
            placeholder="What makes you special? Don't think too hard, just have fun with it."
            className={errors.bio ? styles.inputError : ''}
          />
          {errors.bio && <span className={styles.validationMessage}>{errors.bio.message}</span>}
        </div>

        <div className={styles.formActions}>
          <button
            type="submit"
            disabled={!isDirty || !isValid || isProcessing} // Keep !isValid check
            className={styles.submitButton}
          >
            {isProcessing ? 'Saving...' : 'Save Changes'}
          </button>
        </div>
      </form>
    </div>
  );
};

export default UpdateProfile;
