// frontend-React/src/pages/Home/Home.tsx
import React, { useState, useRef, useEffect } from 'react';
import CreateTweet from '../../components/Tweet/CreateTweet/CreateTweet';
import TweetList from '../../components/Tweet/TweetList/TweetList';
import styles from './Home.module.css';

const Home: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'forYou' | 'following'>('forYou');
  const containerRef = useRef<HTMLDivElement>(null);

  const handleTabChange = (tab: 'forYou' | 'following') => {
    if (activeTab === tab) return;
    setActiveTab(tab);
  };

   useEffect(() => {
     if (containerRef.current) {
       containerRef.current.scrollTop = 0;
     }
   }, [activeTab]);

   const handleTweetCreated = () => {
      // Potentially force a re-fetch or update of the 'For you' list if on that tab
      // Or simply let the optimistic UI update from CreateTweet handle it visually
      console.log('New tweet created, Home page notified.');
      if (activeTab === 'forYou') {
         // Consider a mechanism to refresh the 'forYou' list
         // For now, changing listKey to force re-render, though more sophisticated state management might be better
         setActiveTab('forYou'); // This will trigger useEffect if we add a new key based on this
      }
   }

  return (
    <div className={styles.homeContainer} ref={containerRef}>
      <div className={styles.stickyHeader}> 
        <div className={styles.switchBtn}>
          <button
            className={`${styles.btn} ${activeTab === 'forYou' ? styles.active : ''}`}
            onClick={() => handleTabChange('forYou')}
          >
            For you
          </button>
          <button
            className={`${styles.btn} ${activeTab === 'following' ? styles.active : ''}`}
            onClick={() => handleTabChange('following')}
          >
            Following
          </button>
        </div>
        <div className={styles.createTweetContainer}>
           <CreateTweet onTweetCreated={handleTweetCreated} />
        </div>
      </div>

      <div className={styles.tweetListContainer}>
          <TweetList 
            fetchType={activeTab === 'forYou' ? 'trending' : 'following'} 
            listKey={activeTab} 
          />
      </div>
    </div>
  );
};

export default Home;

// frontend/src/app/home/home.component.ts
import { Component, ElementRef, ViewChild, AfterViewInit, Renderer2 } from '@angular/core';
import { TweetListComponent } from '../tweet/tweet-list/tweet-list.component';
import { CreateTweetComponent } from '../tweet/create-tweet/create-tweet.component';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-home',
  imports: [CreateTweetComponent, TweetListComponent, CommonModule],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent implements AfterViewInit {
  activeTab: 'forYou' | 'following' = 'forYou';
  listKey: string = 'forYou';

  @ViewChild('homeContainer') homeContainer!: ElementRef;

  constructor(private renderer: Renderer2) { }

  ngAfterViewInit(): void {
    // Initial scroll setup or logic if needed
  }

  handleTabChange(tab: 'forYou' | 'following'): void {
    if (this.activeTab === tab) return;
    this.activeTab = tab;
    this.listKey = `${tab}-${Date.now()}`; // Force re-render of TweetList
    if (this.homeContainer.nativeElement) {
      this.homeContainer.nativeElement.scrollTop = 0;
    }
  }

  handleTweetCreated(): void {
    if (this.activeTab === 'forYou') {
        this.listKey = `forYou-${Date.now()}`; // Force re-fetch for 'For you' tab
    }
     // If on 'following' tab, new tweet won't appear unless user follows themselves, or logic is added
  }

  onScroll(): void {
    // Placeholder for scroll-based actions if needed, e.g., lazy loading header animations
  }
}

<div class="homeContainer" #homeContainer (scroll)="onScroll()">
    <div class="stickyHeader"> 
        <div class="switchBtn">
          <button
            class="btn {{ activeTab === 'forYou' ? 'active' : '' }}"
            (click)="handleTabChange('forYou')"
          >
            For you
          </button>
          <button
            class="btn {{ activeTab === 'following' ? 'active' : '' }}"
            (click)="handleTabChange('following')"
          >
            Following
          </button>
        </div>
        <div class="createTweetContainer">
           <app-create-tweet (tweetCreated)="handleTweetCreated()"></app-create-tweet>
        </div>
      </div>

    <div class="tweetListContainer">
        <app-tweet-list 
            [fetchType]="activeTab === 'forYou' ? 'trending' : 'following'" 
            [listKey]="listKey">
        </app-tweet-list>
    </div>
</div>
