// frontend-React/src/components/Reply/NestedReply/NestedReply.tsx
import React, { useState, useEffect, useCallback } from 'react';
import SingleReply from '../SingleReply/SingleReply';
import { ReplyDetails } from '../../../types/reply/replyDetails';
import styles from './NestedReply.module.css'; 
import { getNestedRepliesByParentReplyId } from '../../../services/replyService';

interface NestedReplyProps {
  parentReplyId: number;
  onOpenReplyPopup: (replyId: number) => void;
}

const NestedReply: React.FC<NestedReplyProps> = ({ parentReplyId, onOpenReplyPopup }) => {
  const [nestedReplies, setNestedReplies] = useState<ReplyDetails[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const loadNestedReplies = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      const replies = await getNestedRepliesByParentReplyId(parentReplyId);
      
      const repliesWithState = replies.map(r => ({ ...r, showNested: false }));
      setNestedReplies(repliesWithState);
    } catch (err) {
      console.error('Failed to load nested replies:', err);
      setError('Could not load replies.');
    } finally {
      setIsLoading(false);
    }
  }, [parentReplyId]);

  useEffect(() => {
    loadNestedReplies();
  }, [loadNestedReplies]); 

  const toggleNestedReplies = (replyId: number) => {
    setNestedReplies(prevReplies => 
        prevReplies.map(reply => 
            reply.id === replyId ? { ...reply, showNested: !reply.showNested } : reply
        )
    );
  };

  if (isLoading) {
    return <div className={styles.loading}>Loading replies...</div>;
  }

  if (error) {
    return <div className={styles.error}>{error}</div>;
  }

  return (
    <div className={styles.nestedRepliesContainer}> 
      {nestedReplies.map((nestedReply) => (
        <div key={nestedReply.id}>
          <SingleReply 
            reply={nestedReply} 
            onOpenReplyPopup={onOpenReplyPopup}
            onToggleNested={nestedReply.hasNestedReplies ? () => toggleNestedReplies(nestedReply.id) : undefined}
            isNestedVisible={!!nestedReply.showNested}
          />
          {nestedReply.showNested && (
             <div className={styles.deeplyNested}> 
                 <NestedReply 
                    parentReplyId={nestedReply.id} 
                    onOpenReplyPopup={onOpenReplyPopup} 
                 />
            </div>
          )}
        </div>
      ))}
    </div>
  );
};

export default NestedReply;

// frontend/src/app/reply/nested-reply/nested-reply.component.ts
import { Component, EventEmitter, Input, OnInit, Output, forwardRef } from '@angular/core';
import { SingleReplyComponent } from '../single-reply/single-reply.component';
import { ReplyDetails } from '../../model/reply/replyDetails';
import { ReplyService } from '../../model/reply/replyService';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-nested-reply',
  imports: [SingleReplyComponent, CommonModule, forwardRef(() => NestedReplyComponent)],
  templateUrl: './nested-reply.component.html',
  styleUrl: './nested-reply.component.css'
})
export class NestedReplyComponent implements OnInit {
  @Input() parentReplyId!: number;
  @Output() openReplyPopup = new EventEmitter<number>();

  nestedReplies: ReplyDetails[] = [];
  isLoading = false;
  error: string | null = null;

  constructor(private replyService: ReplyService) { }

  ngOnInit(): void {
    this.loadNestedReplies();
  }

  loadNestedReplies(): void {
    this.isLoading = true;
    this.error = null;
    this.replyService.getNestedRepliesByParentReplyId(this.parentReplyId).subscribe({
      next: replies => {
        this.nestedReplies = replies.map(r => ({ ...r, showNested: false }));
        this.isLoading = false;
      },
      error: err => {
        console.error('Failed to load nested replies:', err);
        this.error = 'Could not load replies.';
        this.isLoading = false;
      }
    });
  }

  onToggleNested(replyId: number): void {
    this.nestedReplies = this.nestedReplies.map(reply => 
        reply.id === replyId ? { ...reply, showNested: !reply.showNested } : reply
    );
  }
  
  onOpenReplyPopup(replyId: number): void {
    this.openReplyPopup.emit(replyId);
  }
}

@if (isLoading) {
    <div class="loading">Loading replies...</div>
}
@if (error) {
    <div class="error">{{error}}</div>
}
@if (!isLoading && !error) {
    <div class="nestedRepliesContainer">
        @for (nestedReply of nestedReplies; track nestedReply.id) {
            <div>
                <app-single-reply 
                    [reply]="nestedReply" 
                    (openReplyPopup)="onOpenReplyPopup($event)"
                    (toggleNested)="onToggleNested($event)"
                    [isNestedVisible]="nestedReply.showNested">
                </app-single-reply>
                @if (nestedReply.showNested) {
                    <div class="deeplyNested">
                        <app-nested-reply 
                            [parentReplyId]="nestedReply.id" 
                            (openReplyPopup)="onOpenReplyPopup($event)">
                        </app-nested-reply>
                    </div>
                }
            </div>
        }
    </div>
}
