// frontend-React/src/components/RightSidebar/RightSidebar.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import styles from './RightSidebar.module.css';
import { getTrendingHashtags } from '../../services/hashtagService';
import { autocompleteSearch } from '../../services/searchService';
import { TrendingHashtagDetails } from '../../types/hashtag/trendingHashtagDetails';
import { AutocompleteResponse, AutocompleteUser, AutocompleteHashtag } from '../../types/search/autocompleteResponse';
import { HttpConfig } from '../../config/http-config';

const RightSidebar: React.FC = () => {
  const [trendingHashtags, setTrendingHashtags] = useState<TrendingHashtagDetails[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [searchResults, setSearchResults] = useState<AutocompleteResponse | null>(null);
  const [isSearchLoading, setIsSearchLoading] = useState(false);
  const [showResults, setShowResults] = useState(false);
  const navigate = useNavigate();

  useEffect(() => {
    const fetchTrending = async () => {
      try {
        const data = await getTrendingHashtags();
        setTrendingHashtags(data);
      } catch (error) {
        console.error('Failed to fetch trending hashtags:', error);
      }
    };
    fetchTrending();
  }, []);

  const handleSearchChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const query = event.target.value;
    console.log("Search Input Change:", query);
    setSearchQuery(query);
    if (query.trim() === '') {
      setSearchResults(null);
      setShowResults(false);
    } else {
      setShowResults(true);
      debouncedSearch(query);
    }
  };

  const performSearch = async (query: string) => {
    console.log("Performing search for:", query);
    if (query.trim() === '') {
      setSearchResults(null);
      return;
    }
    setIsSearchLoading(true);
    try {
      const data = await autocompleteSearch(query);
      console.log("Search results received:", data);
      setSearchResults(data);
    } catch (error) {
      console.error('Autocomplete search failed:', error);
      setSearchResults(null);
    } finally {
      setIsSearchLoading(false);
    }
  };

  const debounce = <F extends (...args: any[]) => any>(
    func: F,
    delay: number
  ) => {
    let timeoutId: ReturnType<typeof setTimeout>;
    return (...args: Parameters<F>): void => {
      clearTimeout(timeoutId);
      timeoutId = setTimeout(() => func(...args), delay);
    };
  };

  // eslint-disable-next-line react-hooks/exhaustive-deps
  const debouncedSearch = useCallback(debounce(performSearch, 300), []);

  // Changed from onClick to onMouseDown
  const handleResultClick = useCallback((item: AutocompleteUser | AutocompleteHashtag, type: 'user' | 'hashtag') => {
    console.log(`Autocomplete: Item clicked - Type: ${type}, ID: ${'id' in item ? item.id : 'N/A'}`, item);
    // Note: Using onMouseDown fires before onBlur, helping prevent the element disappearing
    // No need for e.stopPropagation() or e.preventDefault() here, as onMouseDown completes before blur

    setSearchQuery('');
    setSearchResults(null);
    setShowResults(false); // Hide results immediately on click

    if (type === 'user') {
      const userItem = item as AutocompleteUser;
      console.log(`Autocomplete: Navigating to /profile/${userItem.id}`);
      navigate(`/profile/${userItem.id}`);
    } else {
      const hashtagItem = item as AutocompleteHashtag;
      console.log(`Autocomplete: Navigating to /explore/tag/${hashtagItem.id}/${encodeURIComponent(hashtagItem.tag)}`);
      navigate(`/explore/tag/${hashtagItem.id}/${encodeURIComponent(hashtagItem.tag)}`);
    }
  }, [navigate]);

  const formatCount = (count: number): string => {
    if (count >= 1000000) return (count / 1000000).toFixed(1) + 'M posts';
    if (count >= 1000) return (count / 1000).toFixed(0) + 'K posts';
    return count + ' posts';
  };

  return (
    <aside className={styles.sidebarContainer}>
      <div className={styles.searchBarContainer}>
        <input
          type="text"
          placeholder="Search"
          className={styles.searchInput}
          value={searchQuery}
          onChange={handleSearchChange}
          onFocus={() => {
            console.log("Search input focused. Show results if query exists.");
            searchQuery.trim() !== '' && setShowResults(true);
          }}
          onBlur={() => {
            console.log("Search input blurred. Delaying hide.");
            // Delay hiding results to allow click/mousedown event on suggestions to fire
            setTimeout(() => {
              console.log("Search: Hiding results after delay (200ms).");
              setShowResults(false);
            }, 200); // Increased delay to 200ms
          }}
        />
        {showResults && (searchResults || isSearchLoading) && (
          <div className={styles.autocompleteResults}>
            {isSearchLoading && <div className={styles.loadingText}>Loading...</div>}
            {/* Render users */}
            {searchResults?.users?.map(user => (
              <div
                key={`user-${user.id}`}
                className={styles.autocompleteItem}
                // Use onMouseDown instead of onClick - fires before onBlur
                onMouseDown={() => handleResultClick(user, 'user')}
              >
                <img src={user.profilePicture ? `${HttpConfig.baseUrl}${user.profilePicture}` : '/icons/default-avatar.png'} alt={user.nickname} className={styles.itemImage} />
                <span className={styles.itemName}>{user.nickname}</span>
                <span className={styles.itemType}>User</span>
              </div>
            ))}
            {/* Render hashtags */}
            {searchResults?.hashtags?.map(hashtag => (
              <div
                key={`tag-${hashtag.id}`}
                className={styles.autocompleteItem}
                // Use onMouseDown instead of onClick - fires before onBlur
                 onMouseDown={() => handleResultClick(hashtag, 'hashtag')}
              >
                <span className={styles.itemName}>#{hashtag.tag}</span>
                <span className={styles.itemType}>Hashtag</span>
              </div>
            ))}
            {/* No results message */}
            {!isSearchLoading && !searchResults?.users?.length && !searchResults?.hashtags?.length && searchQuery.trim() !== '' && (
                <div className={styles.loadingText}>No results for "{searchQuery}"</div>
            )}
          </div>
        )}
      </div>

      <div className={styles.widget}>
        <h2 className={styles.widgetTitle}>Trends</h2>
        {trendingHashtags.length > 0 ? (
            <ul className={styles.trendList}>
            {trendingHashtags.map(trend => (
                <li key={trend.id} className={styles.trendItem} onClick={() => navigate(`/explore/tag/${trend.id}/${encodeURIComponent(trend.tag)}`)}>
                <div className={styles.trendCategory}>Trending</div>
                <div className={styles.trendName}>#{trend.tag}</div>
                <div className={styles.trendCount}>{formatCount(trend.count)}</div>
                </li>
            ))}
            </ul>
        ) : (
            <div className={styles.loadingText}>Loading trends...</div>
        )}
      </div>
    </aside>
  );
};

export default RightSidebar;

// frontend/src/app/right-sidebar/right-sidebar.component.ts
/* import { Component, OnInit, OnDestroy } from '@angular/core';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { Subject } from 'rxjs';
import { debounceTime, distinctUntilChanged, switchMap, takeUntil, catchError, filter } from 'rxjs/operators';
import { HashtagService } from '../model/hashtag/hashtagService';
import { SearchService } from '../model/search/searchService';
import { TrendingHashtagDetails } from '../model/hashtag/trendingHashtagDetails';
import { AutocompleteResponse, AutocompleteUser, AutocompleteHashtag } from '../model/search/autocompleteResponse';
import { HttpConfig } from '../config/http-config';

@Component({
  selector: 'app-right-sidebar',
  imports: [FormsModule, CommonModule],
  templateUrl: './right-sidebar.component.html',
  styleUrl: './right-sidebar.component.css'
})
export class RightSidebarComponent implements OnInit, OnDestroy {
  trendingHashtags: TrendingHashtagDetails[] = [];
  searchQuery: string = '';
  searchResults: AutocompleteResponse | null = null;
  isSearchLoading: boolean = false;
  showResults: boolean = false;
  
  private searchSubject = new Subject<string>();
  private destroy$ = new Subject<void>();

  constructor(
    private hashtagService: HashtagService,
    private searchService: SearchService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.fetchTrendingHashtags();
    this.setupSearchDebounce();
  }

  fetchTrendingHashtags(): void {
    this.hashtagService.getTrendingHashtags()
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: data => this.trendingHashtags = data,
        error: err => console.error('Failed to fetch trending hashtags:', err)
      });
  }

  setupSearchDebounce(): void {
    this.searchSubject.pipe(
      takeUntil(this.destroy$),
      filter(query => query.trim().length > 0),
      debounceTime(300),
      distinctUntilChanged(),
      switchMap(query => {
        this.isSearchLoading = true;
        return this.searchService.autocompleteSearch(query).pipe(
            catchError(error => {
                console.error('Autocomplete search failed:', error);
                this.searchResults = null;
                this.isSearchLoading = false;
                return []; // Return empty array on error to prevent stream termination
            })
        );
      })
    ).subscribe({
        next: data => {
            this.searchResults = data;
            this.isSearchLoading = false;
        }
    });
  }

  onSearchChange(query: string): void {
    this.searchQuery = query;
    if (query.trim() === '') {
      this.searchResults = null;
      this.showResults = false;
      this.isSearchLoading = false;
    } else {
      this.showResults = true;
      this.searchSubject.next(query);
    }
  }

  setShowResults(show: boolean): void {
      this.showResults = show;
  }

  onSearchBlur(): void {
    setTimeout(() => this.showResults = false, 150); // Delay to allow click
  }

  handleResultClick(item: AutocompleteUser | AutocompleteHashtag, type: 'user' | 'hashtag'): void {
    this.searchQuery = '';
    this.searchResults = null;
    this.showResults = false;
    if (type === 'user') {
      this.router.navigate([`/profile/${(item as AutocompleteUser).id}`]);
    } else {
      const hashtagItem = item as AutocompleteHashtag;
      this.router.navigate([`/explore/tag/${hashtagItem.id}/${encodeURIComponent(hashtagItem.tag)}`]);
    }
  }
  
  navigateToHashtag(hashtag: TrendingHashtagDetails): void {
      this.router.navigate([`/explore/tag/${hashtag.id}/${encodeURIComponent(hashtag.tag)}`]);
  }

  getFullImageUrl(profilePicturePath?: string): string {
    if (!profilePicturePath) {
      return '/icons/default-avatar.png';
    }
    return `${HttpConfig.baseUrl}${profilePicturePath}`;
  }

  formatCount(count: number): string {
    if (count >= 1000000) return (count / 1000000).toFixed(1) + 'M posts';
    if (count >= 1000) return (count / 1000).toFixed(0) + 'K posts';
    return count + ' posts';
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }
}
 */

import { Component, OnInit, OnDestroy } from '@angular/core';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { Subject, of } from 'rxjs';
import { debounceTime, distinctUntilChanged, switchMap, takeUntil, catchError, filter, map, tap, finalize } from 'rxjs/operators';
import { HashtagService } from '../model/hashtag/hashtagService';
import { SearchService } from '../model/search/searchService';
import { TrendingHashtagDetails } from '../model/hashtag/trendingHashtagDetails';
import { AutocompleteResponse, AutocompleteUser, AutocompleteHashtag } from '../model/search/autocompleteResponse';
import { HttpConfig } from '../config/http-config';

@Component({
  selector: 'app-right-sidebar',
  imports: [FormsModule, CommonModule],
  templateUrl: './right-sidebar.component.html',
  styleUrl: './right-sidebar.component.css'
})
export class RightSidebarComponent implements OnInit, OnDestroy {
  trendingHashtags: TrendingHashtagDetails[] = [];
  searchQuery: string = '';
  searchResults: AutocompleteResponse | null = null;
  isSearchLoading: boolean = false;
  showResults: boolean = false;
  
  private searchSubject = new Subject<string>();
  private destroy$ = new Subject<void>();

  constructor(
    private hashtagService: HashtagService,
    private searchService: SearchService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.fetchTrendingHashtags();
    this.setupSearchDebounce();
  }

  fetchTrendingHashtags(): void {
    this.hashtagService.getTrendingHashtags()
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: data => this.trendingHashtags = data,
        error: err => console.error('Failed to fetch trending hashtags:', err)
      });
  }

  setupSearchDebounce(): void {
    this.searchSubject.pipe(
      takeUntil(this.destroy$),
      map(query => query.trim()),       // 1. Trim the query immediately
      debounceTime(200),              // 2. Debounce (reduced from 300ms for better perceived first-letter responsiveness)
      distinctUntilChanged(),         // 3. Only proceed if the trimmed query has actually changed
      tap(trimmedQuery => {            // Handle UI for empty query after debounce/distinct
        if (trimmedQuery.length === 0) {
          this.searchResults = null;
          this.isSearchLoading = false;
          this.showResults = false;
        } else {
            // If we reached here with a non-empty query, results should be potentially shown
            // and loading will be set before the API call.
        }
      }),
      filter(trimmedQuery => trimmedQuery.length > 0), // 4. Filter out empty strings AFTER debounce and distinct
      tap(() => {
          this.isSearchLoading = true; // Set loading true right before switchMap
          this.showResults = true; // Ensure results overlay is shown
      }), 
      switchMap(trimmedQuery =>
        this.searchService.autocompleteSearch(trimmedQuery).pipe(
          catchError(error => {
            console.error('Autocomplete search failed:', error);
            this.searchResults = null; // Clear results on error
            return of(null as AutocompleteResponse | null); // Return null to keep stream alive
          }),
          finalize(() => this.isSearchLoading = false) // Always set loading to false when inner observable completes/errors
        )
      )
    ).subscribe(data => {
      this.searchResults = data; // Update results (could be null from catchError)
    });
  }

  onSearchChange(query: string): void {
    // this.searchQuery is updated by ngModel
    // Push the raw query to the subject; the stream will handle trimming.
    this.searchSubject.next(query);

    // Immediate UI update for showing/hiding results based on raw input,
    // stream will later refine searchResults and loading state.
    if (query.trim() === '') {
      this.showResults = false;
      // isSearchLoading and searchResults are handled by the stream when it processes the empty query
    } else {
      this.showResults = true; // Show results container immediately for non-empty input
    }
  }
  
  // This method is for the (focus) event in the template, but might not be strictly necessary
  // if onSearchChange and the stream handle showResults appropriately.
  // Keeping it for now as it was in the original structure.
  setShowResults(show: boolean): void {
      if (this.searchQuery.trim() !== '') { // Only show if there's actual text
        this.showResults = show;
      } else {
        this.showResults = false;
      }
  }

  onSearchBlur(): void {
    // Delay hiding results to allow click on items in the autocomplete list
    setTimeout(() => this.showResults = false, 150); 
  }

  handleResultClick(item: AutocompleteUser | AutocompleteHashtag, type: 'user' | 'hashtag'): void {
    this.searchQuery = ''; // Clear search input
    this.searchResults = null;
    this.showResults = false;
    this.searchSubject.next(''); // Push empty to reset stream state if needed

    if (type === 'user') {
      this.router.navigate([`/profile/${(item as AutocompleteUser).id}`]);
    } else {
      const hashtagItem = item as AutocompleteHashtag;
      this.router.navigate([`/explore/tag/${hashtagItem.id}/${encodeURIComponent(hashtagItem.tag)}`]);
    }
  }
  
  navigateToHashtag(hashtag: TrendingHashtagDetails): void {
      this.router.navigate([`/explore/tag/${hashtag.id}/${encodeURIComponent(hashtag.tag)}`]);
  }

  getFullImageUrl(profilePicturePath?: string): string {
    if (!profilePicturePath) {
      return '/icons/default-avatar.png';
    }
    return `${HttpConfig.baseUrl}${profilePicturePath}`;
  }

  formatCount(count: number): string {
    if (count >= 1000000) return (count / 1000000).toFixed(1) + 'M posts';
    if (count >= 1000) return (count / 1000).toFixed(0) + 'K posts';
    return count + ' posts';
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }
}
<aside class="sidebarContainer">
    <div class="searchBarContainer">
      <input 
        type="text" 
        placeholder="Search" 
        class="searchInput"
        [(ngModel)]="searchQuery"
        (ngModelChange)="onSearchChange($event)"
        (focus)="searchQuery.trim() !== '' && setShowResults(true)"
        (blur)="onSearchBlur()"
      />
      @if (showResults && (searchResults || isSearchLoading)) {
        <div class="autocompleteResults">
          @if (isSearchLoading) {
            <div class="loadingText">Loading...</div>
          }
          @for (user of searchResults?.users; track user.id) {
            <div class="autocompleteItem" (mousedown)="handleResultClick(user, 'user')">
              <img [src]="getFullImageUrl(user.profilePicture)" [alt]="user.nickname" class="itemImage" />
              <span class="itemName">{{user.nickname}}</span>
              <span class="itemType">User</span>
            </div>
          }
          @for (hashtag of searchResults?.hashtags; track hashtag.id) {
            <div class="autocompleteItem" (mousedown)="handleResultClick(hashtag, 'hashtag')">
              <span class="itemName">#{{hashtag.tag}}</span>
              <span class="itemType">Hashtag</span>
            </div>
          }
          @if (!isSearchLoading && !searchResults?.users?.length && !searchResults?.hashtags?.length && searchQuery.trim() !== '') {
              <div class="loadingText">No results for "{{searchQuery}}"</div>
          }
        </div>
      }
    </div>
  
    <div class="widget">
      <h2 class="widgetTitle">Trends</h2>
      @if (trendingHashtags.length > 0) {
        <ul class="trendList">
          @for (trend of trendingHashtags; track trend.id) {
            <li class="trendItem" (click)="navigateToHashtag(trend)">
              <div class="trendCategory">Trending</div>
              <div class="trendName">#{{trend.tag}}</div>
              <div class="trendCount">{{formatCount(trend.count)}}</div>
            </li>
          }
        </ul>
      } @else {
        <div class="loadingText">Loading trends...</div>
      }
    </div>
  </aside>
