// frontend-React/src/components/Tweet/TweetList/TweetList.tsx
import React, { useState, useEffect, useRef, useCallback } from 'react';
import SingleTweet from '../SingleTweet/SingleTweet';
import { DisplayTweetDetails } from '../../../types/tweet/displayTweetDetails';
import styles from './TweetList.module.css';
import { getFollowedUsersTweets, getTweets, getTweetsByUserId, getBookmarkedTweets, getTweetsByHashtagId } from '../../../services/tweetService';
import { useSelector } from 'react-redux';
import { selectUserId } from '../../../store/slices/authSlice';

interface TweetListProps {
  // propUserId is the userId passed for viewing a specific user's tweets/bookmarks (e.g. on a profile page)
  userId?: number;
  hashtagId?: number;
  listKey: string;
  fetchType: 'trending' | 'following' | 'user' | 'bookmarks' | 'hashtag';
  onTweetUnbookmarked?: (tweetId: number) => void;
}

const TweetList: React.FC<TweetListProps> = ({ userId: propUserId, hashtagId, listKey, fetchType, onTweetUnbookmarked }) => {
  const [tweets, setTweets] = useState<DisplayTweetDetails[]>([]);
  const [page, setPage] = useState(0);
  const [isLoading, setIsLoading] = useState(false);
  const [hasMoreTweets, setHasMoreTweets] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const observer = useRef<IntersectionObserver>();
  const size = 10;
  const loggedInUserId = useSelector(selectUserId); // This can be number | null

  const listKeyRef = useRef(listKey);

  const loadTweets = useCallback(async (currentPage: number) => {
    if (currentPage > 0 && (isLoading || !hasMoreTweets)) return;
    if (currentPage === 0 && isLoading && listKey === listKeyRef.current) return;

    listKeyRef.current = listKey;
    setIsLoading(true);
    setError(null);

    try {
      let response;

      // Determine the effective user ID for 'user' or 'bookmarks' fetch types
      let effectiveUserIdForFetch: number | null = null;
      if (fetchType === 'user') {
        effectiveUserIdForFetch = propUserId !== undefined ? propUserId : loggedInUserId;
      } else if (fetchType === 'bookmarks') {
        effectiveUserIdForFetch = propUserId !== undefined ? propUserId : loggedInUserId;
      }


      switch (fetchType) {
        case 'trending':
          response = await getTweets(currentPage, size);
          break;
        case 'following':
          if (!loggedInUserId) {
            setError("Please log in to see tweets from users you follow.");
            setHasMoreTweets(false); setIsLoading(false); setTweets([]); return;
          }
          response = await getFollowedUsersTweets(currentPage, size);
          break;
        case 'user':
          if (effectiveUserIdForFetch === null) { // Check if still null after logic above
            // This case implies viewing a generic user profile without a specific ID,
            // or the loggedInUserId is null when it's expected.
            // Or propUserId was undefined and loggedInUserId is null
            setError("User ID is required to fetch user tweets but was not available.");
            setHasMoreTweets(false); setIsLoading(false); setTweets([]); return;
          }
          response = await getTweetsByUserId(effectiveUserIdForFetch, currentPage, size);
          break;
        case 'bookmarks':
          if (effectiveUserIdForFetch === null) { // Check if still null
            setError("Please log in to see bookmarks.");
            setHasMoreTweets(false); setIsLoading(false); setTweets([]); return;
          }
          response = await getBookmarkedTweets(effectiveUserIdForFetch, currentPage, size);
          break;
        case 'hashtag':
          if (hashtagId === undefined) {
            setError('Hashtag ID is required for hashtag tweets.');
            setHasMoreTweets(false); setIsLoading(false); setTweets([]); return;
          }
          response = await getTweetsByHashtagId(hashtagId, currentPage, size);
          break;
        default:
          // Should not happen with TypeScript, but good for safety
          const exhaustiveCheck: never = fetchType;
          throw new Error(`Invalid fetch type: ${exhaustiveCheck}`);
      }

      if (!response || !response.content) {
        throw new Error("Invalid API response structure");
      }

      setHasMoreTweets(currentPage + 1 < response.totalPages);
      setTweets(prev => {
          const newTweets = response.content;
          if (currentPage === 0) return newTweets;
          const existingIds = new Set(prev.map(t => t.id));
          return [...prev, ...newTweets.filter(t => !existingIds.has(t.id))];
      });
      setPage(currentPage + 1);

    } catch (err) {
      console.error(`Failed to load tweets (fetchType: ${fetchType}):`, err);
      setError((err instanceof Error ? err.message : 'Could not load tweets') + '. Please try again later.');
      setHasMoreTweets(false);
    } finally {
      setIsLoading(false);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [fetchType, propUserId, hashtagId, loggedInUserId, size, listKey]); // listKey added here for safety, though useEffect below primarily handles it

  useEffect(() => {
    console.log(`TweetList EFFECT: listKey changed or initial mount. listKey: ${listKey}. FetchType: ${fetchType}. PropUserID: ${propUserId}`);
    setTweets([]);
    setPage(0);
    setHasMoreTweets(true);
    setError(null);
    loadTweets(0);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [listKey]); // loadTweets is memoized and will use the latest propUserId, loggedInUserId etc.

  const lastTweetElementRef = useCallback((node: HTMLDivElement) => {
    if (isLoading || !hasMoreTweets) return;
    if (observer.current) observer.current.disconnect();

    observer.current = new IntersectionObserver(entries => {
      if (entries[0].isIntersecting) {
        console.log("TweetList: Last element visible, loading more.");
        loadTweets(page);
      }
    }, { threshold: 0.5 });

    if (node) observer.current.observe(node);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isLoading, hasMoreTweets, page, loadTweets]); // Added loadTweets here


  const handleLocalBookmarkChange = (updatedTweetFromServer: DisplayTweetDetails) => {
    console.log(`TweetList: Received bookmark change for tweet ID ${updatedTweetFromServer.id}. New state:`, updatedTweetFromServer);

    if (fetchType === 'bookmarks' && !updatedTweetFromServer.bookmarked) {
      setTweets(prevTweets => prevTweets.filter(t => t.id !== updatedTweetFromServer.id));
      if (onTweetUnbookmarked) {
          onTweetUnbookmarked(updatedTweetFromServer.id);
      }
    } else {
      setTweets(prevTweets =>
        prevTweets.map(t =>
          t.id === updatedTweetFromServer.id ? updatedTweetFromServer : t
        )
      );
    }
  };

  if (isLoading && page === 0) {
    return <div className={styles.loading}>Loading tweets...</div>;
  }
  if (error) {
    return <div className={styles.error}>{error}</div>;
  }
  if (!isLoading && tweets.length === 0 && !hasMoreTweets) { // This condition means loading finished, no tweets, and no more pages.
    return <div className={styles.endMessage}>No tweets to show.</div>;
  }

  return (
    <div className={styles.tweetsContainer}>
      {tweets.map((tweetItem, index) => (
        <div key={tweetItem.id} ref={index === tweets.length - 1 ? lastTweetElementRef : null}>
          <SingleTweet
            tweet={tweetItem}
            onBookmarkChange={handleLocalBookmarkChange}
          />
        </div>
      ))}
      {/* Show loading indicator for subsequent pages only if there are already tweets */}
      {isLoading && tweets.length > 0 && <div className={styles.loading}>Loading more tweets...</div>}
      {/* Show end message only if not loading, no more tweets, and some tweets were actually loaded */}
      {!isLoading && !hasMoreTweets && tweets.length > 0 && <div className={styles.endMessage}>End of tweets.</div>}
    </div>
  );
};

export default TweetList;

// frontend/src/app/tweet/tweet-list/tweet-list.component.ts
/* import { Component, Input, OnChanges, OnInit, SimpleChanges, OnDestroy, ViewChild, ElementRef, AfterViewInit, Output, EventEmitter } from '@angular/core';
import { SingleTweetComponent } from '../single-tweet/single-tweet.component';
import { DisplayTweetDetails } from '../../model/tweet/displayTweetDetails';
import { TweetService } from '../../model/tweet/tweetService';
import { AuthService } from '../../model/authentication/authService';
import { CommonModule } from '@angular/common';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

@Component({
  selector: 'app-tweet-list',
  imports: [SingleTweetComponent, CommonModule],
  templateUrl: './tweet-list.component.html',
  styleUrl: './tweet-list.component.css'
})
export class TweetListComponent implements OnInit, OnChanges, OnDestroy, AfterViewInit {
  @Input() userId?: number;
  @Input() hashtagId?: number;
  @Input() listKey!: string; 
  @Input() fetchType!: 'trending' | 'following' | 'user' | 'bookmarks' | 'hashtag';
  @Output() tweetUnbookmarked = new EventEmitter<number>();

  tweets: DisplayTweetDetails[] = [];
  page = 0;
  size = 10;
  isLoading = false;
  hasMoreTweets = true;
  error: string | null = null;
  private loggedInUserId: number | null = null;
  private intersectionObserver?: IntersectionObserver;
  private destroy$ = new Subject<void>();

  @ViewChild('tweetListContainer') tweetListContainer!: ElementRef;

  constructor(
    private tweetService: TweetService,
    private authService: AuthService
  ) { }

  ngOnInit(): void {
    this.authService.userId$.pipe(takeUntil(this.destroy$)).subscribe(id => {
        this.loggedInUserId = id;
        this.resetAndLoadTweets(); 
    });
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['listKey'] || changes['fetchType'] || changes['userId'] || changes['hashtagId']) {
        if(!changes['listKey']?.firstChange && !changes['fetchType']?.firstChange && !changes['userId']?.firstChange && !changes['hashtagId']?.firstChange){
             this.resetAndLoadTweets();
        }
    }
  }
  
  ngAfterViewInit(): void {
    this.setupIntersectionObserver();
  }

  resetAndLoadTweets(): void {
    this.tweets = [];
    this.page = 0;
    this.hasMoreTweets = true;
    this.error = null;
    this.isLoading = false;
    this.loadTweets(0);
  }

  loadTweets(currentPage: number): void {
    if (this.isLoading || (!this.hasMoreTweets && currentPage > 0)) return;
    if (currentPage === 0 && this.isLoading && this.tweets.length > 0) return; 

    this.isLoading = true;
    this.error = null;

    let observable;
    switch (this.fetchType) {
      case 'trending':
        observable = this.tweetService.getTweets(currentPage, this.size);
        break;
      case 'following':
        if (!this.loggedInUserId) {
          this.error = "Please log in to see tweets from users you follow.";
          this.handleLoadingCompletion();
          return;
        }
        observable = this.tweetService.getFollowedUsersTweets(currentPage, this.size);
        break;
      case 'user':
        if (this.userId === undefined) {
            this.error = 'User ID is required for user tweets.';
            this.handleLoadingCompletion();
            return;
        }
        observable = this.tweetService.getTweetsByUserId(this.userId, currentPage, this.size);
        break;
      case 'bookmarks':
        if (this.userId === undefined) { // Should be loggedInUserId for bookmarks
            this.error = 'User ID is required for bookmarks.';
            this.handleLoadingCompletion();
            return;
        }
        observable = this.tweetService.getBookmarkedTweets(this.userId, currentPage, this.size);
        break;
      case 'hashtag':
        if (this.hashtagId === undefined) {
            this.error = 'Hashtag ID is required for hashtag tweets.';
            this.handleLoadingCompletion();
            return;
        }
        observable = this.tweetService.getTweetsByHashtagId(this.hashtagId, currentPage, this.size);
        break;
      default:
        this.error = 'Invalid fetch type for tweets.';
        this.handleLoadingCompletion();
        return;
    }

    observable.pipe(takeUntil(this.destroy$)).subscribe({
      next: response => {
        if (!response || !response.content) {
            this.error = "Invalid API response structure";
            this.handleLoadingCompletion(false);
            return;
        }
        const morePagesExist = (currentPage + 1) < response.totalPages;
        this.hasMoreTweets = morePagesExist;

        if (response.content.length === 0 && currentPage === 0) {
          this.tweets = [];
        } else if (response.content.length > 0) {
          const existingIds = new Set(this.tweets.map(t => t.id));
          const newTweets = response.content.filter(t => !existingIds.has(t.id));
          this.tweets = currentPage === 0 ? response.content : [...this.tweets, ...newTweets];
          this.page = currentPage + 1;
        }
        this.isLoading = false;
        setTimeout(() => this.observeLastElement(), 0); 
      },
      error: err => {
        console.error('Failed to load tweets:', err);
        this.error = (err.message || 'Could not load tweets') + '. Please try again later.';
        this.handleLoadingCompletion(false);
      }
    });
  }

  private handleLoadingCompletion(hasMore = false): void {
    this.isLoading = false;
    this.hasMoreTweets = hasMore;
    if (!hasMore && this.tweets.length === 0 && !this.error) {
      // this.error = "No tweets to show"; // Or set a specific message
    }
  }

  setupIntersectionObserver(): void {
    const options = { root: this.tweetListContainer?.nativeElement, threshold: 0.5 };
    this.intersectionObserver = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting && this.hasMoreTweets && !this.isLoading) {
          this.loadTweets(this.page);
        }
      });
    }, options);
    this.observeLastElement();
  }

  observeLastElement(): void {
    if (this.intersectionObserver && this.tweetListContainer?.nativeElement) {
      this.intersectionObserver.disconnect();
      const lastElement = this.tweetListContainer.nativeElement.querySelector('.last-element');
      if (lastElement) {
        this.intersectionObserver.observe(lastElement);
      }
    }
  }

  onScroll(): void {
    // Manual scroll check can be a fallback or primary if IntersectionObserver is problematic
    if (this.tweetListContainer && !this.isLoading && this.hasMoreTweets) {
        const el = this.tweetListContainer.nativeElement;
        if (el.scrollHeight - el.scrollTop <= el.clientHeight + 100) { // 100px threshold
            this.loadTweets(this.page);
        }
    }
  }

  handleLocalBookmarkChange(event: { tweetId: number, isBookmarked: boolean }): void {
    if (this.fetchType === 'bookmarks' && !event.isBookmarked) {
      this.tweets = this.tweets.filter(t => t.id !== event.tweetId);
      this.tweetUnbookmarked.emit(event.tweetId);
    } else {
      this.tweets = this.tweets.map(t =>
        t.id === event.tweetId ? { ...t, bookmarked: event.isBookmarked, bookmarkId: event.isBookmarked ? t.bookmarkId || -1 : undefined } : t
      );
    }
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
    if (this.intersectionObserver) {
      this.intersectionObserver.disconnect();
    }
  }
}
 */

import { Component, Input, OnChanges, OnInit, SimpleChanges, OnDestroy, ViewChild, ElementRef, AfterViewInit, Output, EventEmitter } from '@angular/core';
import { SingleTweetComponent } from '../single-tweet/single-tweet.component';
import { DisplayTweetDetails } from '../../model/tweet/displayTweetDetails';
import { TweetService } from '../../model/tweet/tweetService';
import { AuthService } from '../../model/authentication/authService';
import { CommonModule } from '@angular/common';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

@Component({
  selector: 'app-tweet-list',
  imports: [SingleTweetComponent, CommonModule],
  templateUrl: './tweet-list.component.html',
  styleUrl: './tweet-list.component.css'
})
export class TweetListComponent implements OnInit, OnChanges, OnDestroy, AfterViewInit {
  @Input() userId?: number;
  @Input() hashtagId?: number;
  @Input() listKey!: string; 
  @Input() fetchType!: 'trending' | 'following' | 'user' | 'bookmarks' | 'hashtag';
  @Output() tweetUnbookmarked = new EventEmitter<number>(); // Used by BookmarksPageComponent

  tweets: DisplayTweetDetails[] = [];
  page = 0;
  size = 10;
  isLoading = false;
  hasMoreTweets = true;
  error: string | null = null;
  private loggedInUserId: number | null = null;
  private intersectionObserver?: IntersectionObserver;
  private destroy$ = new Subject<void>();

  @ViewChild('tweetListContainer') tweetListContainer!: ElementRef;

  constructor(
    private tweetService: TweetService,
    private authService: AuthService
  ) { }

  ngOnInit(): void {
    this.authService.userId$.pipe(takeUntil(this.destroy$)).subscribe(id => {
        this.loggedInUserId = id;
        if (this.listKey && this.fetchType) { // Ensure essential inputs are present
            this.resetAndLoadTweets(); 
        }
    });
  }

  ngOnChanges(changes: SimpleChanges): void {
    let relevantChange = false;
    for (const propName in changes) {
      if (changes.hasOwnProperty(propName) && ['listKey', 'fetchType', 'userId', 'hashtagId'].includes(propName)) {
        if (!changes[propName].firstChange || propName === 'listKey') { // listKey change always triggers reload
          relevantChange = true;
          break;
        }
      }
    }

    if (relevantChange) {
        this.resetAndLoadTweets();
    }
  }
  
  ngAfterViewInit(): void {
    this.setupIntersectionObserver();
  }

  resetAndLoadTweets(): void {
    this.tweets = [];
    this.page = 0;
    this.hasMoreTweets = true;
    this.error = null;
    this.isLoading = false;
    this.loadTweets(0);
  }

  loadTweets(currentPage: number): void {
    if (this.isLoading || (!this.hasMoreTweets && currentPage > 0) ) return;
    
    this.isLoading = true;
    this.error = null;

    let observable;
    switch (this.fetchType) {
      case 'trending':
        observable = this.tweetService.getTweets(currentPage, this.size);
        break;
      case 'following':
        if (!this.loggedInUserId) {
          this.error = "Please log in to see tweets from users you follow.";
          this.handleLoadingCompletion(false, true);
          return;
        }
        observable = this.tweetService.getFollowedUsersTweets(currentPage, this.size);
        break;
      case 'user':
        if (this.userId === undefined) {
            this.error = 'User ID is required for user tweets.';
            this.handleLoadingCompletion(false, true);
            return;
        }
        observable = this.tweetService.getTweetsByUserId(this.userId, currentPage, this.size);
        break;
      case 'bookmarks':
        if (this.loggedInUserId === undefined || this.loggedInUserId === null) { 
            this.error = 'User ID is required for bookmarks.';
            this.handleLoadingCompletion(false, true);
            return;
        }
        observable = this.tweetService.getBookmarkedTweets(this.loggedInUserId, currentPage, this.size);
        break;
      case 'hashtag':
        if (this.hashtagId === undefined) {
            this.error = 'Hashtag ID is required for hashtag tweets.';
            this.handleLoadingCompletion(false, true);
            return;
        }
        observable = this.tweetService.getTweetsByHashtagId(this.hashtagId, currentPage, this.size);
        break;
      default:
        this.error = 'Invalid fetch type for tweets.';
        this.handleLoadingCompletion(false, true);
        return;
    }

    observable.pipe(takeUntil(this.destroy$)).subscribe({
      next: response => {
        if (!response || !response.content) {
            this.error = "Invalid API response structure";
            this.handleLoadingCompletion(false);
            return;
        }
        const morePagesExist = (currentPage + 1) < response.totalPages;
        this.hasMoreTweets = morePagesExist;

        if (response.content.length === 0 && currentPage === 0) {
          this.tweets = [];
        } else if (response.content.length > 0) {
          const existingIds = new Set(this.tweets.map(t => t.id));
          const newTweets = response.content.filter(t => !existingIds.has(t.id));
          this.tweets = currentPage === 0 ? response.content : [...this.tweets, ...newTweets];
          this.page = currentPage + 1;
        }
        this.isLoading = false;
        setTimeout(() => this.observeLastElement(), 0); 
      },
      error: err => {
        console.error('Failed to load tweets:', err);
        this.error = (err.message || 'Could not load tweets') + '. Please try again later.';
        this.handleLoadingCompletion(false);
      }
    });
  }

  private handleLoadingCompletion(hasMore = false, clearTweetsOnError = false): void {
    this.isLoading = false;
    this.hasMoreTweets = hasMore;
    if (clearTweetsOnError && this.error) {
        this.tweets = [];
    }
  }

  setupIntersectionObserver(): void {
    if (!this.tweetListContainer?.nativeElement) return;
    const options = { root: null, threshold: 0.5 }; 
    this.intersectionObserver = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting && this.hasMoreTweets && !this.isLoading) {
          this.loadTweets(this.page);
        }
      });
    }, options);
    this.observeLastElement();
  }

  observeLastElement(): void {
    if (this.intersectionObserver && this.tweetListContainer?.nativeElement) {
      this.intersectionObserver.disconnect(); 
      const lastElement = this.tweetListContainer.nativeElement.querySelector('.last-element');
      if (lastElement) {
        this.intersectionObserver.observe(lastElement);
      }
    }
  }

  onScroll(): void {
    // Fallback or primary scroll detection. Currently IntersectionObserver is primary.
  }

  handleLocalBookmarkChange(event: { tweetId: number, isBookmarked: boolean, newBookmarkCount: number, newBookmarkId?: number }): void {
    if (this.fetchType === 'bookmarks' && !event.isBookmarked) {
      this.tweets = this.tweets.filter(t => t.id !== event.tweetId);
      this.tweetUnbookmarked.emit(event.tweetId);
    } else {
      this.tweets = this.tweets.map(t =>
        t.id === event.tweetId ? { 
            ...t, 
            bookmarked: event.isBookmarked, 
            bookmarkId: event.isBookmarked ? event.newBookmarkId : undefined,
            bookmarkCount: event.newBookmarkCount // Update the count from the event
        } : t
      );
    }
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
    if (this.intersectionObserver) {
      this.intersectionObserver.disconnect();
    }
  }
}
<div class="tweetsContainer" #tweetListContainer (scroll)="onScroll()">
    @for (tweet of tweets; track tweet.id; let idx = $index) {
      <div [attr.data-tweet-id]="tweet.id" [class.last-element]="idx === tweets.length - 1">
        <app-single-tweet [tweet]="tweet" (bookmarkChange)="handleLocalBookmarkChange($event)"></app-single-tweet>
      </div>
    }
    @if (isLoading) {
      <div class="loading">Loading...</div>
    }
    @if (!isLoading && !hasMoreTweets && tweets.length > 0) {
      <div class="endMessage">End of tweets</div>
    }
    @if (!isLoading && !hasMoreTweets && tweets.length === 0 && !error) {
      <div class="endMessage">No tweets to show</div>
    }
    @if (error) {
      <div class="error">{{error}}</div>
    }
  </div>
