// frontend/src/app/authentication/login/login.component.ts
import { Component, EventEmitter, Output, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { LoginDetails } from '../../model/authentication/loginDetails';
import { AuthService } from '../../model/authentication/authService';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-login',
  imports: [ReactiveFormsModule, CommonModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})
export class LoginComponent implements OnInit {
  loginForm!: FormGroup;
  @Output() closeModal = new EventEmitter<void>();

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(8)]]
    });
  }

  onSubmit(): void {
    if (this.loginForm.valid) {
      const formData: LoginDetails = this.loginForm.value;

      this.authService.login(formData).subscribe({
        next: response => {
          this.authService.setAuth(response.token);
          this.closeModal.emit();
          this.router.navigate(['/home']);
        },
        error: err => {
          console.error('Login failed:', err);
          alert('Login failed. Check credentials and try again.');
        }
      });
    } else {
      this.loginForm.markAllAsTouched();
    }
  }
}

<div class="loginContainer">
    <h2>Log in to your account</h2>
    <form (ngSubmit)="onSubmit()" [formGroup]="loginForm" class="loginForm">
        <div class="formGroup">
            <label for="email">Email</label>
            <input type="email" id="email" formControlName="email" [class.inputError]="loginForm.get('email')?.invalid && loginForm.get('email')?.touched">
            @if (loginForm.get('email')?.invalid && loginForm.get('email')?.touched) {
                <span class="validationMessage">
                    @if (loginForm.get('email')?.errors?.['required']) {
                        Email is required
                    }
                    @if (loginForm.get('email')?.errors?.['email']) {
                        Invalid email format
                    }
                </span>
            }
        </div>
        <div class="formGroup">
            <label for="password">Password</label>
            <input type="password" id="password" formControlName="password" [class.inputError]="loginForm.get('password')?.invalid && loginForm.get('password')?.touched">
            @if (loginForm.get('password')?.invalid && loginForm.get('password')?.touched) {
                <span class="validationMessage">
                    @if (loginForm.get('password')?.errors?.['required']) {
                        Password is required
                    }
                    @if (loginForm.get('password')?.errors?.['minlength']) {
                        Password must be at least 8 characters
                    }
                </span>
            }
        </div>

        <button type="submit" [disabled]="!loginForm.valid" class="submitBtn">
          Login
        </button>
    </form>
</div>

// frontend-React/src/components/Authentication/Login/Login.tsx
import React from 'react';
import { useForm, SubmitHandler } from 'react-hook-form';
import { LoginDetails } from '../../../types/authentication/loginDetails';
import { login as loginUser } from '../../../services/authService';
import styles from './Login.module.css';
import { useDispatch } from 'react-redux';
import { setAuth } from '../../../store/slices/authSlice';
import { AppDispatch } from '../../../store/store';

interface LoginProps {
    onClose: () => void;
}

const Login: React.FC<LoginProps> = ({ onClose }) => {
  const dispatch = useDispatch<AppDispatch>();
  const { register, handleSubmit, formState: { errors, isValid } } = useForm<LoginDetails>({
      mode: 'onChange'
  });

  const onSubmit: SubmitHandler<LoginDetails> = async (data) => {
    try {
      const response = await loginUser(data);
      dispatch(setAuth({ token: response.token }));
      onClose(); 
      
    } catch (error) {
      console.error('Login failed:', error);
      alert('Login failed. Check credentials and try again.'); 
    }
  };

  return (
    <div className={styles.loginContainer}>
        <h2>Log in to your account</h2>
      <form onSubmit={handleSubmit(onSubmit)} className={styles.loginForm}>
        <div className={styles.formGroup}>
          <label htmlFor="email">Email</label>
          <input
            type="email"
            id="email"
            {...register('email', { required: 'Email is required', pattern: { value: /^\S+@\S+$/i, message: 'Invalid email format' } })}
             className={errors.email ? styles.inputError : ''}
          />
          {errors.email && <span className={styles.validationMessage}>{errors.email.message}</span>}
        </div>
        <div className={styles.formGroup}>
          <label htmlFor="password">Password</label>
          <input
            type="password"
            id="password"
            {...register('password', { required: 'Password is required', minLength: { value: 8, message: 'Password must be at least 8 characters' } })}
            className={errors.password ? styles.inputError : ''}
          />
           {errors.password && <span className={styles.validationMessage}>{errors.password.message}</span>}
        </div>

        <button type="submit" disabled={!isValid} className={styles.submitBtn}>
          Login
        </button>
      </form>
    </div>
  );
};

export default Login;
