// frontend/src/app/tweet/tweet-detail/tweet-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { SingleTweetComponent } from '../single-tweet/single-tweet.component';
import { CreateReplyComponent } from '../../reply/create-reply/create-reply.component';
import { ReplyListComponent } from '../../reply/reply-list/reply-list.component';
import { DisplayTweetDetails } from '../../model/tweet/displayTweetDetails';
import { ReplyDetails } from '../../model/reply/replyDetails';
import { TweetService } from '../../model/tweet/tweetService';

@Component({
  selector: 'app-tweet-detail',
  imports: [RouterModule, CommonModule, SingleTweetComponent, CreateReplyComponent, ReplyListComponent],
  templateUrl: './tweet-detail.component.html',
  styleUrl: './tweet-detail.component.css'
})
export class TweetDetailComponent implements OnInit {
  tweet: DisplayTweetDetails | null = null;
  isLoading = true;
  error: string | null = null;
  newReplyForList: ReplyDetails | null = null;
  showReplyModal = false;
  parentReplyId: number | null = null;
  tweetId: number | null = null;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private tweetService: TweetService
  ) { }

  ngOnInit(): void {
    const idParam = this.route.snapshot.paramMap.get('id');
    if (idParam) {
      this.tweetId = Number(idParam);
      this.loadTweetDetails();
    } else {
      this.error = 'Tweet ID not provided.';
      this.isLoading = false;
    }
  }

  loadTweetDetails(): void {
    if (!this.tweetId) return;
    this.isLoading = true;
    this.error = null;
    this.tweetService.findTweetById(this.tweetId).subscribe({
      next: data => {
        this.tweet = data;
        this.isLoading = false;
      },
      error: err => {
        console.error("Failed to load tweet details:", err);
        this.error = 'Could not load tweet.';
        this.isLoading = false;
      }
    });
  }

  openReplyPopup(replyId: number): void {
    this.parentReplyId = replyId;
    this.showReplyModal = true;
  }

  closeReplyPopup(): void {
    this.showReplyModal = false;
    this.parentReplyId = null;
  }

  handleReplyCreated(createdReply: ReplyDetails): void {
    if (this.tweet) {
      this.tweet.replyCount = (this.tweet.replyCount || 0) + 1;
    }
    if (!createdReply.parentReplyId) {
      this.newReplyForList = { ...createdReply }; 
    }
    if (this.showReplyModal) {
      this.closeReplyPopup();
    }
  }

  goBack(): void {
    this.router.navigate(['/home']);
  }
}

<div class="pageContainer">
    <div class="headerBar">
        <button (click)="goBack()" class="backButton">
            <img src="/icons/back-arrow.svg" alt="Go Back" class="arrowIcon" />
        </button>
        <span class="headerTitle">Post</span>
    </div>

    @if (tweet) {
        <div class="tweetDetailContent">
            <app-single-tweet [tweet]="tweet" [isDetailView]="true"></app-single-tweet>
        </div>

        @if (showReplyModal) {
            <div class="overlay" (click)="closeReplyPopup()">
                <div class="modal replyModal" (click)="$event.stopPropagation()">
                    <button class="close-btn customCloseBtn" (click)="closeReplyPopup()">&times;</button>
                    <app-create-reply 
                        [tweetId]="tweetId!"
                        [parentReplyId]="parentReplyId"
                        (replyCreated)="handleReplyCreated($event)">
                    </app-create-reply>
                </div>
            </div>
        }

        <div class="createReplyContainer">
            <app-create-reply 
                [tweetId]="tweetId!" 
                [parentReplyId]="null"
                (replyCreated)="handleReplyCreated($event)">
            </app-create-reply>
        </div>

        <div class="repliesContainer">
            <app-reply-list 
                [tweetId]="tweetId!" 
                [newReply]="newReplyForList" 
                (openReplyPopup)="openReplyPopup($event)"
                [listKey]="'tweet-' + tweetId + '-replies'">
            </app-reply-list>
        </div>
    } @else if (isLoading) {
        <div>Loading tweet...</div>
    } @else if (error) {
        <div>{{error}}</div>
    } @else {
        <div>Tweet not found.</div>
    }
</div>

// frontend-React/src/pages/TweetDetail/TweetDetail.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import SingleTweet from '../../components/Tweet/SingleTweet/SingleTweet';
import CreateReply from '../../components/Reply/CreateReply/CreateReply';
import ReplyList from '../../components/Reply/ReplyList/ReplyList';
import { DisplayTweetDetails } from '../../types/tweet/displayTweetDetails';
import { ReplyDetails } from '../../types/reply/replyDetails';
import styles from './TweetDetail.module.css';
import { findTweetById } from '../../services/tweetService';
import backIcon from '../../assets/icons/back-arrow.svg';

const TweetDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [tweet, setTweet] = useState<DisplayTweetDetails | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [newReply, setNewReply] = useState<ReplyDetails | null>(null);
  const [showReplyModal, setShowReplyModal] = useState(false);
  const [parentReplyId, setParentReplyId] = useState<number | null>(null);

  const tweetId = Number(id);

  const loadTweetDetails = useCallback(async () => {
    if (!tweetId) return;
    setIsLoading(true);
    setError(null);
    try {
      const data = await findTweetById(tweetId);
      setTweet(data);
    } catch (err) {
      console.error("Failed to load tweet details:", err);
      setError('Could not load tweet.');
    } finally {
      setIsLoading(false);
    }
  }, [tweetId]);

  useEffect(() => {
    loadTweetDetails();
  }, [loadTweetDetails]);

  const openReplyPopup = (replyId: number) => {
    setParentReplyId(replyId);
    setShowReplyModal(true);
  };

  const closeReplyPopup = () => {
    setShowReplyModal(false);
    setParentReplyId(null);
  };

  const handleReplyCreated = (createdReply: ReplyDetails) => {
    // Update reply count on the main tweet
    setTweet(prev => prev ? { ...prev, replyCount: prev.replyCount + 1 } : null);
    // Pass the new reply to the ReplyList component to prepend it (if it's a main reply)
    if (!createdReply.parentReplyId) {
        setNewReply(createdReply);
    }
    // Close the modal if it was open for a nested reply
    if (showReplyModal) {
       closeReplyPopup(); 
    }
  };

  const goBack = () => {
    navigate('/home');
  };

  if (isLoading) {
    return <div>Loading tweet...</div>;
  }

  if (error) {
    return <div>{error}</div>;
  }

  if (!tweet) {
    return <div>Tweet not found.</div>;
  }

  return (
    <div className={styles.pageContainer}>
       <div className={styles.headerBar}>
          <button onClick={goBack} className={styles.backButton}>
             <img src={backIcon} alt="Go Back" className={styles.arrowIcon} />
          </button>
          <span className={styles.headerTitle}>Post</span>
       </div>
      
       <div className={styles.tweetContainer}>
         <SingleTweet tweet={tweet} isDetailView={true}/>
       </div>

      
      {showReplyModal && (
        <div className="overlay" onClick={closeReplyPopup}>
          <div className={`modal ${styles.replyModal}`} onClick={e => e.stopPropagation()}> 
             <button className={`close-btn ${styles.customCloseBtn}`} onClick={closeReplyPopup}>&times;</button>
            <CreateReply 
              tweetId={tweetId}
              parentReplyId={parentReplyId} // Pass the ID of the reply being replied to
              onReplyCreated={handleReplyCreated}
            />
          </div>
        </div>
      )}

      
      <div className={styles.createReplyContainer}>
        <CreateReply 
            tweetId={tweetId} 
            parentReplyId={null} // Main reply creator at the bottom
            onReplyCreated={handleReplyCreated} 
        />
      </div>

      <div className={styles.repliesContainer}>
        <ReplyList 
          tweetId={tweetId} 
          newReply={newReply} // Pass the newly created main reply
          onOpenReplyPopup={openReplyPopup} // Function to open the nested reply modal
          listKey={`tweet-${tweetId}-replies`}
        />
      </div>
    </div>
  );
};

export default TweetDetail;
