// frontend/src/app/reply/reply-list/reply-list.component.ts
import { Component, EventEmitter, Input, OnChanges, OnInit, Output, SimpleChanges, ViewChild, ElementRef, OnDestroy } from '@angular/core';
import { SingleReplyComponent } from '../single-reply/single-reply.component';
import { ReplyDetails } from '../../model/reply/replyDetails';
import { ReplyService } from '../../model/reply/replyService';
import { NestedReplyComponent } from '../nested-reply/nested-reply.component';
import { CommonModule } from '@angular/common';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

@Component({
  selector: 'app-reply-list',
  imports: [SingleReplyComponent, NestedReplyComponent, CommonModule],
  templateUrl: './reply-list.component.html',
  styleUrl: './reply-list.component.css'
})
export class ReplyListComponent implements OnInit, OnChanges, OnDestroy {
  @Input() tweetId?: number;
  @Input() userId?: number; 
  @Input() newReply?: ReplyDetails | null;
  @Input() listKey!: string; // To help Angular detect changes and re-render/re-fetch
  @Output() openReplyPopup = new EventEmitter<number>();

  mainReplies: ReplyDetails[] = [];
  page = 0;
  size = 10;
  isLoading = false;
  hasMoreReplies = true;

  @ViewChild('repliesContainer') repliesContainer!: ElementRef;
  private destroy$ = new Subject<void>();

  constructor(private replyService: ReplyService) { }

  ngOnInit(): void {
    this.loadInitialReplies();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['newReply'] && this.newReply && !this.newReply.parentReplyId) {
      this.mainReplies = [this.newReply, ...this.mainReplies];
    }
    if (changes['listKey'] && !changes['listKey'].firstChange) {
      this.resetAndLoadReplies();
    }
    if ((changes['tweetId'] && !changes['tweetId'].firstChange) || (changes['userId'] && !changes['userId'].firstChange)){
      this.resetAndLoadReplies();
    }
  }

  resetAndLoadReplies(): void {
    this.mainReplies = [];
    this.page = 0;
    this.hasMoreReplies = true;
    this.isLoading = false;
    this.loadInitialReplies();
  }

  loadInitialReplies(): void {
    if (this.tweetId !== undefined || this.userId !== undefined) {
      this.loadReplies(0);
    }
  }

  loadReplies(currentPage: number): void {
    if (this.isLoading || !this.hasMoreReplies) return;
    this.isLoading = true;

    let observable;
    if (this.tweetId !== undefined) {
      observable = this.replyService.getMainRepliesByTweetId(this.tweetId, currentPage, this.size);
    } else if (this.userId !== undefined) {
      observable = this.replyService.getRepliesByUserId(this.userId, currentPage, this.size);
    } else {
      this.isLoading = false;
      return;
    }

    observable.pipe(takeUntil(this.destroy$)).subscribe({
      next: response => {
        const processedReplies = response.content.map(reply => ({
            ...reply,
            hasNestedReplies: reply.hasNestedReplies === undefined ? false : reply.hasNestedReplies,
            showNested: false
        }));

        if (response.content.length === 0 && currentPage === 0) {
          this.mainReplies = [];
          this.hasMoreReplies = false;
        } else if (response.content.length > 0) {
          this.mainReplies = currentPage === 0 ? processedReplies : [...this.mainReplies, ...processedReplies];
          this.page = currentPage + 1;
          this.hasMoreReplies = (currentPage + 1) < response.totalPages;
        } else {
            this.hasMoreReplies = false;
        }
        this.isLoading = false;
      },
      error: err => {
        console.error('Failed to load replies:', err);
        this.isLoading = false;
      }
    });
  }

  onScroll(): void {
    if (!this.repliesContainer || this.isLoading || !this.hasMoreReplies) return;
    const element = this.repliesContainer.nativeElement;
    const tolerance = 50;
    const isNearBottom = element.scrollHeight - element.scrollTop <= element.clientHeight + tolerance;

    if (isNearBottom) {
      this.loadReplies(this.page);
    }
  }

  onToggleNested(replyId: number): void {
     this.mainReplies = this.mainReplies.map(reply => 
        reply.id === replyId ? { ...reply, showNested: !reply.showNested } : reply
    );
  }

  onOpenReplyPopup(replyId: number): void {
    this.openReplyPopup.emit(replyId);
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }
}

<div class="repliesContainer" #repliesContainer (scroll)="onScroll()">
  @for (mainReply of mainReplies; track mainReply.id) {
    <div>
      <app-single-reply 
        [reply]="mainReply" 
        (openReplyPopup)="onOpenReplyPopup($event)"
        (toggleNested)="onToggleNested($event)"
        [isNestedVisible]="mainReply.showNested">
      </app-single-reply>
      @if (mainReply.showNested) {
        <div class="nestedReplies">
            <app-nested-reply 
                [parentReplyId]="mainReply.id" 
                (openReplyPopup)="onOpenReplyPopup($event)">
            </app-nested-reply>
        </div>
      }
    </div>
  }
  @if (isLoading) {
    <div class="loading">Loading more replies...</div>
  }
  @if (!hasMoreReplies && mainReplies.length > 0) {
    <div class="endMessage">No more replies</div>
  }
  @if (!hasMoreReplies && mainReplies.length === 0) {
    <div class="endMessage">No replies to show</div>
  }
</div>

// frontend-React/src/components/Reply/ReplyList/ReplyList.tsx
import React, { useState, useEffect, useRef, useCallback } from 'react';
import SingleReply from '../SingleReply/SingleReply';
import NestedReply from '../NestedReply/NestedReply';
import { ReplyDetails } from '../../../types/reply/replyDetails';
import styles from './ReplyList.module.css';
import { getMainRepliesByTweetId, getRepliesByUserId } from '../../../services/replyService';

interface ReplyListProps {
  tweetId?: number;
  userId?: number; 
  newReply?: ReplyDetails | null;
  listKey: string;
  onOpenReplyPopup: (replyId: number) => void;
}

const ReplyList: React.FC<ReplyListProps> = ({ tweetId, userId, newReply, onOpenReplyPopup }) => {
  const [mainReplies, setMainReplies] = useState<ReplyDetails[]>([]);
  const [page, setPage] = useState(0);
  const [isLoading, setIsLoading] = useState(false);
  const [hasMoreReplies, setHasMoreReplies] = useState(true);
  const containerRef = useRef<HTMLDivElement>(null);
  const size = 10;

  const loadReplies = useCallback(async (currentPage: number) => {
    if (isLoading || !hasMoreReplies) return;
    setIsLoading(true);

    try {
      let response;
      if (tweetId !== undefined) {
        response = await getMainRepliesByTweetId(tweetId, currentPage, size);
         response.content.forEach(reply => {
             if (reply.hasNestedReplies === undefined) reply.hasNestedReplies = false; // Initialize if missing
             reply.showNested = false; // Always default to hidden
         });
      } else if (userId !== undefined) {
        response = await getRepliesByUserId(userId, currentPage, size);
        response.content.forEach(reply => {
             reply.hasNestedReplies = false; 
             reply.showNested = false;
        }); 
      } else {
          throw new Error("Either tweetId or userId must be provided");
      }

      if (response.content.length === 0) {
        setHasMoreReplies(false);
      } else {
        setMainReplies(prev => currentPage === 0 ? response.content : [...prev, ...response.content]);
        setPage(currentPage + 1);
        setHasMoreReplies(currentPage + 1 < response.totalPages);
      }
    } catch (error) {
      console.error('Failed to load replies:', error);
      
    } finally {
      setIsLoading(false);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isLoading, hasMoreReplies, tweetId, userId, size]);

  
  useEffect(() => {
    setMainReplies([]);
    setPage(0);
    setHasMoreReplies(true);
    loadReplies(0);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tweetId, userId]); // Rerun when tweetId or userId changes

  
  useEffect(() => {
    if (newReply) {
        if (!newReply.parentReplyId) {
            // Add to main replies if it's not a nested reply
            setMainReplies(prev => [newReply, ...prev]);
        } else {
            // manual refresh for nested 
        }
    }
  }, [newReply]);

  
  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const handleScroll = () => {
      const tolerance = 50; // Load slightly before reaching the absolute bottom
      const isNearBottom = container.scrollHeight - container.scrollTop <= container.clientHeight + tolerance;
      
      if (isNearBottom && !isLoading && hasMoreReplies) {
        loadReplies(page);
      }
    };

    container.addEventListener('scroll', handleScroll);
    return () => container.removeEventListener('scroll', handleScroll);
  }, [loadReplies, isLoading, hasMoreReplies, page]);

  const toggleNestedReplies = (replyId: number) => {
     setMainReplies(prevReplies => 
        prevReplies.map(reply => 
            reply.id === replyId ? { ...reply, showNested: !reply.showNested } : reply
        )
    );
  };

  return (
    <div className={styles.repliesContainer} ref={containerRef}>
      {mainReplies.map((mainReply) => (
        <div key={mainReply.id}>
          <SingleReply 
            reply={mainReply} 
            onOpenReplyPopup={onOpenReplyPopup}
            onToggleNested={mainReply.hasNestedReplies ? () => toggleNestedReplies(mainReply.id) : undefined}
            isNestedVisible={!!mainReply.showNested}
          />
          {mainReply.showNested && (
            <div className={styles.nestedReplies}>
                <NestedReply 
                    parentReplyId={mainReply.id} 
                    onOpenReplyPopup={onOpenReplyPopup} 
                />
            </div>
          )}
        </div>
      ))}
       {isLoading && <div>Loading more replies...</div>}
       {!hasMoreReplies && mainReplies.length > 0 && <div className={styles.endMessage}>No more replies</div>}
       {!hasMoreReplies && mainReplies.length === 0 && <div className={styles.endMessage}>No replies to show</div>}
    </div>
  );
};

export default ReplyList;
