// frontend/src/app/reply/create-reply/create-reply.component.ts
import { AfterViewInit, Component, ElementRef, EventEmitter, Input, OnInit, Output, ViewChild } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ReplyDetails } from '../../model/reply/replyDetails';
import { ReplyService } from '../../model/reply/replyService';
import { AuthService } from '../../model/authentication/authService';
import { CreateReplyDetails } from '../../model/reply/createReplyDetails';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-create-reply',
  imports: [ReactiveFormsModule, CommonModule],
  templateUrl: './create-reply.component.html',
  styleUrl: './create-reply.component.css'
})
export class CreateReplyComponent implements OnInit, AfterViewInit {
  userId: number | null = null;
  replyForm!: FormGroup;
  
  @ViewChild('replyTextarea') replyTextarea!: ElementRef<HTMLTextAreaElement>;

  @Input() tweetId!: number;
  @Input() parentReplyId: number | null = null;
  @Output() replyCreated = new EventEmitter<ReplyDetails>();
  
  constructor(
    private replyService: ReplyService,
    private fb: FormBuilder,
    private authService: AuthService
  ) { }

  ngOnInit(): void {
    this.authService.userId$.subscribe(id => this.userId = id);
    this.replyForm = this.fb.group({
      content: ['', [Validators.required, Validators.maxLength(500)]]
    });
  }

  ngAfterViewInit(): void {
    if (this.replyTextarea) {
      this.adjustTextareaHeight();
    }
  }

  adjustTextareaHeight(): void {
    if (this.replyTextarea) {
      const textarea = this.replyTextarea.nativeElement;
      textarea.style.height = '25px'; 
      textarea.style.height = `${textarea.scrollHeight}px`;
    }
  }

  onSubmit(): void {
    if (this.replyForm.invalid || !this.userId) {
      console.error('Form invalid or user not logged in');
      return;
    }

    const payload: CreateReplyDetails = {
      ...this.replyForm.value,
      userId: this.userId,
      tweetId: this.tweetId,
      parentReplyId: this.parentReplyId
    };

    this.replyService.replyToTweet(payload).subscribe({
      next: newReply => {
        this.replyCreated.emit(newReply);
        this.replyForm.reset();
        this.adjustTextareaHeight();
      },
      error: err => console.error('Failed to post reply:', err)
    });
  }
}

<div class="replyContainer">
    <form [formGroup]="replyForm" (ngSubmit)="onSubmit()" class="replyForm">
        <div class="textareaWrapper">
            <textarea #replyTextarea formControlName="content" rows="1" maxlength="500" placeholder="Post your reply"
                class="textarea" (input)="adjustTextareaHeight()">
            </textarea>
        </div>
        <div class="buttonContainer">
            <button type="submit" [disabled]="!replyForm.valid" class="submitButton">Reply</button>
        </div>
    </form>
</div>

// frontend-React/src/components/Reply/CreateReply/CreateReply.tsx
import React, { useRef, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { ReplyDetails } from '../../../types/reply/replyDetails';
import { CreateReplyDetails } from '../../../types/reply/createReplyDetails';
import styles from './CreateReply.module.css';
import { replyToTweet } from '../../../services/replyService';
import { useSelector } from 'react-redux';
import { selectUserId } from '../../../store/slices/authSlice';

interface CreateReplyProps {
  tweetId: number;
  parentReplyId?: number | null;
  onReplyCreated: (newReply: ReplyDetails) => void;
}

interface FormData {
  content: string;
}

const CreateReply: React.FC<CreateReplyProps> = ({ tweetId, parentReplyId = null, onReplyCreated }) => {
  const userId = useSelector(selectUserId);
  const { register, handleSubmit, reset, watch, formState: { isValid } } = useForm<FormData>({
     mode: 'onChange' 
  });
  const textareaRef = useRef<HTMLTextAreaElement | null>(null);
  const contentValue = watch('content');

  const adjustTextareaHeight = () => {
    if (textareaRef.current) {
      textareaRef.current.style.height = '25px'; 
      textareaRef.current.style.height = `${textareaRef.current.scrollHeight}px`;
    }
  };

  
  useEffect(() => {
    adjustTextareaHeight();
  }, [contentValue]);

  const onSubmit = async (data: FormData) => {
    if (!userId) {
        console.error('User not logged in');
        
        return;
    }

    const payload: CreateReplyDetails = {
      ...data,
      userId: userId,
      tweetId: tweetId,
      parentReplyId: parentReplyId
    };

    try {
      const newReply = await replyToTweet(payload);
      onReplyCreated(newReply);
      reset(); 
      
    } catch (error) {
      console.error('Failed to post reply:', error);
    }
  };

  return (
    <div className={styles.replyContainer}>
      <form onSubmit={handleSubmit(onSubmit)} className={styles.replyForm}>
        <div className={styles.textareaWrapper}>
          <textarea
            {...register('content', { required: true, maxLength: 500 })}
            rows={1}
            maxLength={1000} 
            placeholder="Post your reply"
            className={styles.textarea}
            ref={(e) => {
              register('content').ref(e);
              textareaRef.current = e; 
            }}
          />
           
        </div>
        <div className={styles.buttonContainer}>
          <button type="submit" disabled={!isValid} className={styles.submitButton}>
            Reply
          </button>
        </div>
      </form>
    </div>
  );
};

export default CreateReply;
