// frontend-React/src/components/Tweet/CreateTweet/CreateTweet.tsx
import React, { useRef, useEffect } from 'react';
import { useForm, SubmitHandler } from 'react-hook-form';
import { CreateTweetDetails } from '../../../types/tweet/createTweetDetails';
import styles from './CreateTweet.module.css';
import { HttpConfig } from '../../../config/http-config';
import { createTweet } from '../../../services/tweetService';
import { useSelector } from 'react-redux';
import { selectUserDetails } from '../../../store/slices/userSlice';
import { selectUserId } from '../../../store/slices/authSlice';

interface CreateTweetProps {
   onTweetCreated?: () => void; 
}

interface FormData {
  content: string;
}

const CreateTweet: React.FC<CreateTweetProps> = ({ onTweetCreated }) => {
  const userId = useSelector(selectUserId);
  const userDetails = useSelector(selectUserDetails);
  const { register, handleSubmit, reset, watch, formState: { isValid } } = useForm<FormData>({ mode: 'onChange' });
  const textareaRef = useRef<HTMLTextAreaElement | null>(null);
  const contentValue = watch('content'); 

  const adjustTextareaHeight = () => {
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto'; 
      textareaRef.current.style.height = `${textareaRef.current.scrollHeight}px`;
    }
  };
  
  useEffect(() => {
    adjustTextareaHeight();
  }, [contentValue]);

  const onSubmit: SubmitHandler<FormData> = async (data) => {
    if (!userId) {
      console.error('User not logged in');
      return;
    }

    const payload: CreateTweetDetails = {
      ...data,
      userId: userId
    };

    try {
      await createTweet(payload);
      reset(); 
      if (onTweetCreated) onTweetCreated(); 
      
    } catch (error) {
      console.error('Failed to post tweet:', error);
      alert('Could not post tweet. Please try again.');
    }
  };

  // Use userDetails from Redux for the profile picture
  const profilePictureUrl = userDetails?.profilePicture
      ? `${HttpConfig.baseUrl}${userDetails.profilePicture}`
      : '/icons/default-avatar.png';

  return (
    <div className={styles.createTweetContainer}>
        <div className={styles.inputArea}>
            <img 
                src={profilePictureUrl}
                alt="Your profile picture"
                className={styles.profilePicture}
            />
            <form onSubmit={handleSubmit(onSubmit)} className={styles.tweetForm}>
                <textarea
                    {...register('content', { required: true, maxLength: 1000 })}
                    rows={1}
                    placeholder="What is happening?"
                    className={styles.textarea}
                    ref={(e) => {
                    register('content').ref(e);
                    textareaRef.current = e; 
                    }}
                />
                 
                <div className={styles.actionsContainer}>            
                    <div className={styles.iconsPlaceholder}></div>
                    <button type="submit" disabled={!isValid} className={styles.submitButton}>
                        Post
                    </button>
                 </div>
            </form>
        </div>
    </div>
  );
};


export default CreateTweet;

// frontend/src/app/tweet/create-tweet/create-tweet.component.ts
import { AfterViewInit, Component, ElementRef, OnInit, ViewChild, Output, EventEmitter } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { CreateTweetDetails } from '../../model/tweet/createTweetDetails';
import { TweetService } from '../../model/tweet/tweetService';
import { AuthService } from '../../model/authentication/authService';
import { UserService } from '../../model/user/userService';
import { HttpConfig } from '../../config/http-config';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-create-tweet',
  imports: [ReactiveFormsModule, CommonModule],
  templateUrl: './create-tweet.component.html',
  styleUrl: './create-tweet.component.css'
})
export class CreateTweetComponent implements OnInit, AfterViewInit {
  @ViewChild('tweetTextarea') tweetTextarea!: ElementRef<HTMLTextAreaElement>;
  @Output() tweetCreated = new EventEmitter<void>();
  
  tweetForm!: FormGroup;
  userId: number | null = null;
  profilePictureUrl: string = '/icons/default-avatar.png';

  constructor(
    private tweetService: TweetService,
    private fb: FormBuilder,
    private authService: AuthService,
    private userService: UserService
  ) { }

  ngOnInit(): void {
    this.authService.userId$.subscribe(id => this.userId = id);
    this.userService.userDetails$.subscribe(details => {
      this.profilePictureUrl = details?.profilePicture
        ? `${HttpConfig.baseUrl}${details.profilePicture}`
        : '/icons/default-avatar.png';
    });

    this.tweetForm = this.fb.group({
      content: ['', [Validators.required, Validators.maxLength(1000)]]
    });
  }

  ngAfterViewInit(): void {
    this.adjustTextareaHeight();
  }

  adjustTextareaHeight(): void {
    if (this.tweetTextarea) {
        const textarea = this.tweetTextarea.nativeElement;
        textarea.style.height = 'auto'; 
        textarea.style.height = `${textarea.scrollHeight}px`;
    }
  }

  onSubmit(): void {
    if (this.tweetForm.invalid || !this.userId) {
        console.error('Form invalid or user not logged in');
        return;
    }

    const payload: CreateTweetDetails = {
      ...this.tweetForm.value,
      userId: this.userId
    };

    this.tweetService.createTweet(payload).subscribe({
      next: () => {
        this.tweetForm.reset();
        this.adjustTextareaHeight();
        this.tweetCreated.emit();
      },
      error: err => {
          console.error('Failed to post tweet:', err);
          alert('Could not post tweet. Please try again.');
      }
    });
  }
}

<div class="createTweetContainer">
    <div class="inputArea">
        <img 
            [src]="profilePictureUrl"
            alt="Your profile picture"
            class="profilePicture"
        />
        <form (ngSubmit)="onSubmit()" [formGroup]="tweetForm" class="tweetForm">
            <textarea #tweetTextarea formControlName="content" rows="1" placeholder="What is happening?"
                class="textarea" (input)="adjustTextareaHeight()">
            </textarea>
             
            <div class="actionsContainer">            
                <div class="iconsPlaceholder"></div>
                <button type="submit" [disabled]="!tweetForm.valid" class="submitButton">
                    Post
                </button>
             </div>
        </form>
    </div>
</div>
