// frontend/src/app/tweet/single-tweet/single-tweet.component.ts
/* import { Component, Input, OnInit, OnChanges, SimpleChanges, Output, EventEmitter } from '@angular/core';
import { Router, RouterModule } from '@angular/router';
import { CommonModule, DatePipe } from '@angular/common';
import { DisplayTweetDetails } from '../../model/tweet/displayTweetDetails';
import { HttpConfig } from '../../config/http-config';
import { TweetService } from '../../model/tweet/tweetService';
import { AuthService } from '../../model/authentication/authService';
import { LikeTweetDetails } from '../../model/tweet/likeTweetDetails';
import { BookmarkDetails } from '../../model/tweet/bookmarkDetails';

@Component({
  selector: 'app-single-tweet',
  imports: [RouterModule, CommonModule],
  providers: [DatePipe],
  templateUrl: './single-tweet.component.html',
  styleUrl: './single-tweet.component.css'
})
export class SingleTweetComponent implements OnInit, OnChanges {
  @Input({ required: true }) tweet!: DisplayTweetDetails;
  @Input() isDetailView: boolean = false;
  @Output() bookmarkChange = new EventEmitter<{ tweetId: number, isBookmarked: boolean }>();

  localTweet!: DisplayTweetDetails;
  userId: number | null = null;

  constructor(
    private tweetService: TweetService,
    private authService: AuthService,
    private router: Router,
    private datePipe: DatePipe
  ) { }

  ngOnInit(): void {
    this.authService.userId$.subscribe(id => this.userId = id);
    this.localTweet = { ...this.tweet };
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['tweet']) {
      this.localTweet = { ...this.tweet };
    }
  }

  handleLikeToggle(): void {
    if (!this.userId) return;

    const currentLikeId = this.localTweet.likeId;
    const currentlyLiked = this.localTweet.liked;
    const currentLikeCount = this.localTweet.likeCount;

    this.localTweet.liked = !currentlyLiked;
    this.localTweet.likeCount = currentlyLiked ? currentLikeCount - 1 : currentLikeCount + 1;
    this.localTweet.likeId = currentlyLiked ? undefined : -1; // Placeholder

    if (!currentlyLiked) {
      const likeData: LikeTweetDetails = { userId: this.userId, tweetId: this.localTweet.id };
      this.tweetService.addLikeToTweet(likeData).subscribe({
        next: result => {
          this.localTweet.liked = true;
          this.localTweet.likeCount = result.likeCount;
          this.localTweet.likeId = result.likeId;
        },
        error: () => {
          this.localTweet.liked = currentlyLiked;
          this.localTweet.likeCount = currentLikeCount;
          this.localTweet.likeId = currentLikeId;
          alert("Could not update like status.");
        }
      });
    } else if (currentLikeId) {
      this.tweetService.removeLikeFromTweet(currentLikeId).subscribe({
        next: result => {
          this.localTweet.liked = false;
          this.localTweet.likeCount = result.likeCount;
          this.localTweet.likeId = undefined;
        },
        error: () => {
          this.localTweet.liked = currentlyLiked;
          this.localTweet.likeCount = currentLikeCount;
          this.localTweet.likeId = currentLikeId;
          alert("Could not update like status.");
        }
      });
    }
  }

  handleBookmarkToggle(): void {
    if (!this.userId) return;

    const currentBookmarkId = this.localTweet.bookmarkId;
    const currentlyBookmarked = this.localTweet.bookmarked;
    const currentBookmarkCount = this.localTweet.bookmarkCount;
    const newBookmarkedStatus = !currentlyBookmarked;

    this.localTweet.bookmarked = newBookmarkedStatus;
    this.localTweet.bookmarkCount = currentlyBookmarked ? currentBookmarkCount - 1 : currentBookmarkCount + 1;
    this.localTweet.bookmarkId = currentlyBookmarked ? undefined : -1; // Placeholder

    if (!currentlyBookmarked) {
      const bookmarkData: BookmarkDetails = { userId: this.userId, tweetId: this.localTweet.id };
      this.tweetService.addBookmarkToTweet(bookmarkData).subscribe({
        next: result => {
          this.localTweet.bookmarked = true;
          this.localTweet.bookmarkCount = result.bookmarkCount;
          this.localTweet.bookmarkId = result.bookmarkId;
          this.bookmarkChange.emit({ tweetId: this.localTweet.id, isBookmarked: true });
        },
        error: () => {
          this.localTweet.bookmarked = currentlyBookmarked;
          this.localTweet.bookmarkCount = currentBookmarkCount;
          this.localTweet.bookmarkId = currentBookmarkId;
          alert("Could not update bookmark status.");
        }
      });
    } else if (currentBookmarkId !== undefined) {
      this.tweetService.removeBookmarkFromTweet(currentBookmarkId).subscribe({
        next: result => {
          this.localTweet.bookmarked = false;
          this.localTweet.bookmarkCount = result.bookmarkCount;
          this.localTweet.bookmarkId = undefined;
          this.bookmarkChange.emit({ tweetId: this.localTweet.id, isBookmarked: false });
        },
        error: () => {
          this.localTweet.bookmarked = currentlyBookmarked;
          this.localTweet.bookmarkCount = currentBookmarkCount;
          this.localTweet.bookmarkId = currentBookmarkId;
          alert("Could not update bookmark status.");
        }
      });
    }
  }

  handleReplyClick(): void {
    if (!this.isDetailView) {
      this.router.navigate([`/tweet/${this.localTweet.id}`]);
    }
  }

  navigateToTweet(): void {
    if (!this.isDetailView) {
      this.router.navigate([`/tweet/${this.localTweet.id}`]);
    }
  }

  getFullImageUrl(profilePicturePath: string | null | undefined): string {
    if (!profilePicturePath) {
      return '/icons/default-avatar.png';
    }
    return `${HttpConfig.baseUrl}${profilePicturePath}`;
  }

  formatDateTime(dateTimeString: string | undefined): string {
    if (!dateTimeString) return '';
    try {
      const date = new Date(dateTimeString);
      const formattedDate = this.datePipe.transform(date, 'yyyy-MM-dd');
      const formattedTime = this.datePipe.transform(date, 'HH:mm');
      return `${formattedDate} \u00B7 ${formattedTime}`;
    } catch (error) {
      console.error("Error parsing date string:", error);
      return dateTimeString;
    }
  }
}
 */


import { Component, Input, OnInit, OnChanges, SimpleChanges, Output, EventEmitter } from '@angular/core';
import { Router, RouterModule } from '@angular/router';
import { CommonModule, DatePipe } from '@angular/common';
import { DisplayTweetDetails } from '../../model/tweet/displayTweetDetails';
import { HttpConfig } from '../../config/http-config';
import { TweetService } from '../../model/tweet/tweetService';
import { AuthService } from '../../model/authentication/authService';
import { LikeTweetDetails } from '../../model/tweet/likeTweetDetails';
import { BookmarkDetails } from '../../model/tweet/bookmarkDetails';

@Component({
  selector: 'app-single-tweet',
  imports: [RouterModule, CommonModule],
  providers: [DatePipe],
  templateUrl: './single-tweet.component.html',
  styleUrl: './single-tweet.component.css'
})
export class SingleTweetComponent implements OnInit, OnChanges {
  @Input({ required: true }) tweet!: DisplayTweetDetails;
  @Input() isDetailView: boolean = false;
  @Output() bookmarkChange = new EventEmitter<{ tweetId: number, isBookmarked: boolean, newBookmarkCount: number, newBookmarkId?: number }>();

  localTweet!: DisplayTweetDetails;
  userId: number | null = null;

  constructor(
    private tweetService: TweetService,
    private authService: AuthService,
    private router: Router,
    private datePipe: DatePipe
  ) { }

  ngOnInit(): void {
    this.authService.userId$.subscribe(id => this.userId = id);
    if (this.tweet) {
        this.localTweet = { ...this.tweet };
    }
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['tweet'] && this.tweet) {
      // Update localTweet if the input tweet changes.
      // This ensures that if the parent list updates the tweet data, this component reflects it.
      const currentLocalStateBookmarked = this.localTweet?.bookmarked;
      const currentLocalStateBookmarkId = this.localTweet?.bookmarkId;
      const currentLocalStateBookmarkCount = this.localTweet?.bookmarkCount;

      this.localTweet = { ...this.tweet };

      // Preserve optimistic updates if an API call is in flight (more complex scenario not fully handled here)
      // For simplicity, we assume parent's data is the source of truth when it changes.
      // If an operation just finished and parent list got updated, this ensures localTweet is also in sync.
    }
  }

  handleLikeToggle(): void {
    if (!this.userId || !this.localTweet) return;

    const originalState = {
        liked: this.localTweet.liked,
        likeCount: this.localTweet.likeCount,
        likeId: this.localTweet.likeId
    };

    this.localTweet.liked = !originalState.liked;
    this.localTweet.likeCount = originalState.liked ? originalState.likeCount - 1 : originalState.likeCount + 1;
    this.localTweet.likeId = originalState.liked ? undefined : -1;


    if (!originalState.liked) {
      const likeData: LikeTweetDetails = { userId: this.userId, tweetId: this.localTweet.id };
      this.tweetService.addLikeToTweet(likeData).subscribe({
        next: result => {
          this.localTweet.liked = true;
          this.localTweet.likeCount = result.likeCount;
          this.localTweet.likeId = result.likeId;
        },
        error: () => {
          this.localTweet.liked = originalState.liked;
          this.localTweet.likeCount = originalState.likeCount;
          this.localTweet.likeId = originalState.likeId;
          alert("Could not update like status.");
        }
      });
    } else if (originalState.likeId !== undefined) {
      this.tweetService.removeLikeFromTweet(originalState.likeId).subscribe({
        next: result => {
          this.localTweet.liked = false;
          this.localTweet.likeCount = result.likeCount;
          this.localTweet.likeId = undefined;
        },
        error: () => {
          this.localTweet.liked = originalState.liked;
          this.localTweet.likeCount = originalState.likeCount;
          this.localTweet.likeId = originalState.likeId;
          alert("Could not update like status.");
        }
      });
    }
  }

  handleBookmarkToggle(): void {
    if (!this.userId || !this.localTweet) return;

    const originalState = {
        bookmarked: this.localTweet.bookmarked,
        bookmarkCount: this.localTweet.bookmarkCount,
        bookmarkId: this.localTweet.bookmarkId
    };

    this.localTweet.bookmarked = !originalState.bookmarked;
    this.localTweet.bookmarkCount = originalState.bookmarked ? (originalState.bookmarkCount - 1) : (originalState.bookmarkCount + 1);
    this.localTweet.bookmarkId = originalState.bookmarked ? undefined : -1; // Optimistic: undefined for remove, placeholder for add


    if (!originalState.bookmarked) {
      const bookmarkData: BookmarkDetails = { userId: this.userId, tweetId: this.localTweet.id };
      this.tweetService.addBookmarkToTweet(bookmarkData).subscribe({
        next: result => {
          this.localTweet.bookmarked = true;
          this.localTweet.bookmarkCount = result.bookmarkCount;
          this.localTweet.bookmarkId = result.bookmarkId;
          this.bookmarkChange.emit({
            tweetId: this.localTweet.id,
            isBookmarked: true,
            newBookmarkCount: result.bookmarkCount,
            newBookmarkId: result.bookmarkId
          });
        },
        error: () => {
          this.localTweet.bookmarked = originalState.bookmarked;
          this.localTweet.bookmarkCount = originalState.bookmarkCount;
          this.localTweet.bookmarkId = originalState.bookmarkId;
          alert("Could not update bookmark status.");
        }
      });
    } else if (originalState.bookmarkId !== undefined) {
      this.tweetService.removeBookmarkFromTweet(originalState.bookmarkId).subscribe({
        next: result => {
          this.localTweet.bookmarked = false;
          this.localTweet.bookmarkCount = result.bookmarkCount;
          this.localTweet.bookmarkId = undefined;
          this.bookmarkChange.emit({
            tweetId: this.localTweet.id,
            isBookmarked: false,
            newBookmarkCount: result.bookmarkCount
          });
        },
        error: () => {
          this.localTweet.bookmarked = originalState.bookmarked;
          this.localTweet.bookmarkCount = originalState.bookmarkCount;
          this.localTweet.bookmarkId = originalState.bookmarkId;
          alert("Could not update bookmark status.");
        }
      });
    }
  }

  handleReplyClick(): void {
    if (!this.isDetailView && this.localTweet) {
      this.router.navigate([`/tweet/${this.localTweet.id}`]);
    }
  }

  navigateToTweet(): void {
    if (!this.isDetailView && this.localTweet) {
      this.router.navigate([`/tweet/${this.localTweet.id}`]);
    }
  }

  getFullImageUrl(profilePicturePath: string | null | undefined): string {
    if (!profilePicturePath) {
      return '/icons/default-avatar.png';
    }
    return `${HttpConfig.baseUrl}${profilePicturePath}`;
  }

  formatDateTime(dateTimeString: string | undefined): string {
    if (!dateTimeString) return '';
    try {
      const date = new Date(dateTimeString);
      const formattedDate = this.datePipe.transform(date, 'yyyy-MM-dd');
      const formattedTime = this.datePipe.transform(date, 'HH:mm');
      return `${formattedDate} \u00B7 ${formattedTime}`;
    } catch (error) {
      console.error("Error parsing date string:", error);
      return dateTimeString;
    }
  }
}
<div class="tweetContainer" (click)="navigateToTweet()" role="article" tabindex="0">
    <div class="tweetHeader">
      <a [routerLink]="['/profile', localTweet.userId]" (click)="$event.stopPropagation()" class="profilePicLink">
        <img class="profilePicture"
             [src]="getFullImageUrl(localTweet.userProfilePicture)"
             [alt]="'Profile picture of ' + localTweet.userNickname">
      </a>
      <div class="userInfoContainer">
        <div class="userInfo">
          <a [routerLink]="['/profile', localTweet.userId]" class="nicknameLink" (click)="$event.stopPropagation()">
            <h3 class="nickname">{{ localTweet.userNickname }}</h3>
          </a>
         <p class="time">{{ formatDateTime(localTweet.createdAt) }}</p>
        </div>
        <div class="tweetContent">
          <p>{{ localTweet.content }}</p>
        </div>
      </div>
    </div>

    <div class="actions">
      <div class="interactionButtons">
        <button class="interactionButton likeButton" [class.active]="localTweet.liked" (click)="handleLikeToggle(); $event.stopPropagation()" [attr.aria-label]="localTweet.liked ? 'Unlike' : 'Like'" [attr.aria-pressed]="localTweet.liked">
          <img class="interactionIcon" src="/icons/tweet-buttons/like.svg" alt="Like" />
          <span class="interactionCount">{{ localTweet.likeCount }}</span>
        </button>

        <button class="interactionButton replyButton" (click)="handleReplyClick(); $event.stopPropagation()" aria-label="Reply">
          <img class="interactionIcon" src="/icons/tweet-buttons/reply.svg" alt="Reply" />
          <span class="interactionCount">{{ localTweet.replyCount }}</span>
        </button>

        <button class="interactionButton bookmarkButton" [class.active]="localTweet.bookmarked" (click)="handleBookmarkToggle(); $event.stopPropagation()" [attr.aria-label]="localTweet.bookmarked ? 'Remove bookmark' : 'Bookmark'" [attr.aria-pressed]="localTweet.bookmarked">
          <img class="interactionIcon" src="/icons/tweet-buttons/bookmark.svg" alt="Bookmark" />
          <span class="interactionCount">{{ localTweet.bookmarkCount }}</span>
        </button>
      </div>
    </div>
  </div>

// frontend-React/src/components/Tweet/SingleTweet/SingleTweet.tsx
import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { DisplayTweetDetails } from '../../../types/tweet/displayTweetDetails';
import { HttpConfig } from '../../../config/http-config';
import styles from './SingleTweet.module.css';
import { addBookmarkToTweet, addLikeToTweet, removeBookmarkFromTweet, removeLikeFromTweet } from '../../../services/tweetService';
import { useSelector } from 'react-redux';
import { selectUserId } from '../../../store/slices/authSlice';
import replyIcon from '../../../assets/icons/tweet-buttons/reply.svg';
import likeIcon from '../../../assets/icons/tweet-buttons/like.svg';
import bookmarkIcon from '../../../assets/icons/tweet-buttons/bookmark.svg';
import { format, parseISO } from 'date-fns';
import { it } from 'date-fns/locale/it';

interface SingleTweetProps {
  tweet: DisplayTweetDetails;
  isDetailView?: boolean;
}

const SingleTweet: React.FC<SingleTweetProps> = ({ tweet, isDetailView = false }) => {
  const userId = useSelector(selectUserId);
  const navigate = useNavigate();
  const [localTweet, setLocalTweet] = useState<DisplayTweetDetails>(tweet);

  useEffect(() => {
    setLocalTweet(tweet);
  }, [tweet]);

  const handleLikeToggle = async (event: React.MouseEvent<HTMLButtonElement>) => {
    event.stopPropagation();
    if (!userId) return;

    const currentLikeId = localTweet.likeId;
    const currentlyLiked = localTweet.liked;
    const currentLikeCount = localTweet.likeCount;


    setLocalTweet(prev => ({
      ...prev,
      liked: !currentlyLiked,
      likeCount: currentlyLiked ? currentLikeCount - 1 : currentLikeCount + 1,
      likeId: currentlyLiked ? undefined : -1
    }));

    try {
      if (!currentlyLiked) {
        const likeData = { userId: userId, tweetId: localTweet.id };
        const result = await addLikeToTweet(likeData);

        setLocalTweet(prev => ({ ...prev, likeCount: result.likeCount, likeId: result.likeId, liked: true }));
      } else if (currentLikeId) {
        const result = await removeLikeFromTweet(currentLikeId);

        setLocalTweet(prev => ({ ...prev, likeCount: result.likeCount, likeId: undefined, liked: false }));
      }
    } catch (error) {
      console.error("Failed to toggle like:", error);

      setLocalTweet(prev => ({ ...prev, liked: currentlyLiked, likeCount: currentLikeCount, likeId: currentLikeId }));
      alert("Could not update like status.");
    }
  };

  const handleBookmarkToggle = async (event: React.MouseEvent<HTMLButtonElement>) => {
    event.stopPropagation();
    if (!userId) return;

    const currentBookmarkId = localTweet.bookmarkId;
    const currentlyBookmarked = localTweet.bookmarked;
    const currentBookmarkCount = localTweet.bookmarkCount;


    setLocalTweet(prev => ({
      ...prev,
      bookmarked: !currentlyBookmarked,
      bookmarkCount: currentlyBookmarked ? currentBookmarkCount - 1 : currentBookmarkCount + 1,
      bookmarkId: currentlyBookmarked ? undefined : -1
    }));

    try {
      const currentDate = new Date();
      const creationDate = currentDate.toISOString().split('T')[0];
      const creationTime = currentDate.toISOString().split('T')[1].split('.')[0];

      if (!currentlyBookmarked) {
        const bookmarkData = {
          userId: userId,
          tweetId: localTweet.id,
          creationDate: creationDate,
          creationTime: creationTime
        };
        const result = await addBookmarkToTweet(bookmarkData);
        setLocalTweet(prev => ({
          ...prev,
          bookmarkCount: result.bookmarkCount,
          bookmarkId: result.bookmarkId,
          bookmarked: true
        }));
      } else if (currentBookmarkId !== undefined) {
        const result = await removeBookmarkFromTweet(currentBookmarkId);
        setLocalTweet(prev => ({
          ...prev,
          bookmarkCount: result.bookmarkCount,
          bookmarkId: undefined,
          bookmarked: false
        }));
      }
    } catch (error) {
      console.error("Failed to toggle bookmark:", error);
      setLocalTweet(prev => ({
        ...prev,
        bookmarked: currentlyBookmarked,
        bookmarkCount: currentBookmarkCount,
        bookmarkId: currentBookmarkId
      }));
      alert("Could not update bookmark status.");
    }
  };

  const handleReplyClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    event.stopPropagation();

    if (!isDetailView) {
      navigate(`/tweet/${localTweet.id}`);
    }
  }

  const navigateToTweet = () => {
    if (!isDetailView) {
      navigate(`/tweet/${localTweet.id}`);
    }
  };

  const getFullImageUrl = (profilePicturePath: string | null | undefined) => {
    if (!profilePicturePath) {
      return '/icons/default-avatar.png';
    }
    return `${HttpConfig.baseUrl}${profilePicturePath}`;
  };

  const formatDateTime = (dateTimeString: string | undefined) => {
    if (!dateTimeString) {
      return '';
    }
    try {
      const date = parseISO(dateTimeString);
      const formattedDate = format(date, 'yyyy-MM-dd', { locale: it });
      const formattedTime = format(date, 'HH:mm', { locale: it });
      return `${formattedDate} \u00B7 ${formattedTime}`;
    } catch (error) {
      console.error("Error parsing date string:", error);
      return dateTimeString;
    }
  };

  return (
    <div className={styles.tweetContainer} onClick={navigateToTweet} role="article" tabIndex={0}>
      <div className={styles.tweetHeader}>
        <Link
          to={`/profile/${localTweet.userId}`}
          onClick={(e) => e.stopPropagation()}
          className={styles.profilePicLink}
        >
          <img
            className={styles.profilePicture}
            src={getFullImageUrl(localTweet.userProfilePicture)}
            alt={`Profile picture of ${localTweet.userNickname}`}
          />
        </Link>
        <div className={styles.userInfoContainer}>
          <div className={styles.userInfo}>
            <Link
              to={`/profile/${localTweet.userId}`}
              className={styles.nicknameLink}
              onClick={(e) => e.stopPropagation()}
            >
              <h3 className={styles.nickname}>{localTweet.userNickname}</h3>
            </Link>
           <p className={styles.time}>{formatDateTime(localTweet.createdAt)}</p>
          </div>
          <div className={styles.tweetContent}>
            <p>{localTweet.content}</p>
          </div>
        </div>
      </div>

      <div className={styles.actions}>
        <div className={styles.interactionButtons}>
          <button className={`${styles.interactionButton} ${styles.likeButton} ${localTweet.liked ? styles.active : ''}`} onClick={handleLikeToggle} aria-label={localTweet.liked ? 'Unlike' : 'Like'} aria-pressed={localTweet.liked}>
            <img className={styles.interactionIcon} src={likeIcon} alt="Like" />
            <span className={styles.interactionCount}>{localTweet.likeCount ?? 0}</span>
          </button>

          <button className={`${styles.interactionButton} ${styles.replyButton}`} onClick={handleReplyClick} aria-label="Reply">
            <img className={styles.interactionIcon} src={replyIcon} alt="Reply" />
            <span className={styles.interactionCount}>{localTweet.replyCount ?? 0}</span>
          </button>

          <button className={`${styles.interactionButton} ${styles.bookmarkButton} ${localTweet.bookmarked ? styles.active : ''}`} onClick={handleBookmarkToggle} aria-label={localTweet.bookmarked ? 'Remove bookmark' : 'Bookmark'} aria-pressed={localTweet.bookmarked}>
            <img className={styles.interactionIcon} src={bookmarkIcon} alt="Bookmark" />
            <span className={styles.interactionCount}>{localTweet.bookmarkCount ?? 0}</span>
          </button>
        </div>
      </div>
    </div>
  );
};

export default SingleTweet;
