// frontend/src/app/reply/single-reply/single-reply.component.ts
import { Component, EventEmitter, Input, OnInit, Output, OnChanges, SimpleChanges } from '@angular/core';
import { RouterModule } from '@angular/router';
import { CommonModule, DatePipe } from '@angular/common';
import { ReplyDetails } from '../../model/reply/replyDetails';
import { HttpConfig } from '../../config/http-config';
import { ReplyService } from '../../model/reply/replyService';
import { AuthService } from '../../model/authentication/authService';
import { LikeReplyDetails } from '../../model/reply/likeReplyDetails';

@Component({
  selector: 'app-single-reply',
  imports: [RouterModule, CommonModule],
  providers: [DatePipe],
  templateUrl: './single-reply.component.html',
  styleUrl: './single-reply.component.css'
})
export class SingleReplyComponent implements OnInit, OnChanges {
  @Input({ required: true }) reply!: ReplyDetails;
  @Output() openReplyPopup = new EventEmitter<number>();
  @Output() toggleNested = new EventEmitter<number>();
  @Input() isNestedVisible?: boolean;

  localReply!: ReplyDetails;
  userId: number | null = null;

  constructor(
    private replyService: ReplyService,
    private authService: AuthService,
    private datePipe: DatePipe
  ) { }

  ngOnInit(): void {
    this.authService.userId$.subscribe(id => this.userId = id);
    this.localReply = { ...this.reply };
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['reply']) {
      this.localReply = { ...this.reply };
    }
    if (changes['isNestedVisible']) {
        this.isNestedVisible = changes['isNestedVisible'].currentValue;
    }
  }

  handleLikeToggle(): void {
    if (!this.userId) return;

    const currentLikeId = this.localReply.likeId;
    const currentlyLiked = this.localReply.liked;
    const currentLikeCount = this.localReply.likeCount;

    this.localReply.liked = !currentlyLiked;
    this.localReply.likeCount = currentlyLiked ? currentLikeCount - 1 : currentLikeCount + 1;
    this.localReply.likeId = currentlyLiked ? undefined : -1; // Placeholder

    if (!currentlyLiked) {
      const likeData: LikeReplyDetails = { userId: this.userId, replyId: this.localReply.id };
      this.replyService.addLikeToReply(likeData).subscribe({
        next: result => {
          this.localReply.liked = true;
          this.localReply.likeCount = result.likeCount;
          this.localReply.likeId = result.likeId;
        },
        error: () => {
          this.localReply.liked = currentlyLiked;
          this.localReply.likeCount = currentLikeCount;
          this.localReply.likeId = currentLikeId;
          alert("Could not update like status.");
        }
      });
    } else if (currentLikeId) {
      this.replyService.removeLikeFromReply(currentLikeId).subscribe({
        next: result => {
          this.localReply.liked = false;
          this.localReply.likeCount = result.likeCount;
          this.localReply.likeId = undefined;
        },
        error: () => {
          this.localReply.liked = currentlyLiked;
          this.localReply.likeCount = currentLikeCount;
          this.localReply.likeId = currentLikeId;
          alert("Could not update like status.");
        }
      });
    }
  }

  handleReplyClick(): void {
    this.openReplyPopup.emit(this.localReply.id);
  }

  handleToggleNestedClick(): void {
    this.toggleNested.emit(this.localReply.id);
  }

  getFullImageUrl(profilePicturePath: string | null | undefined): string {
    if (!profilePicturePath) {
      return '/icons/default-avatar.png';
    }
    return `${HttpConfig.baseUrl}${profilePicturePath}`;
  }

  formatDateTime(dateTimeString: string | undefined): string {
    if (!dateTimeString) return '';
    try {
      const date = new Date(dateTimeString);
      // Using date-fns formatting to match React exactly would require adding date-fns to Angular project
      // For now, using Angular's DatePipe which is similar
      const formattedDate = this.datePipe.transform(date, 'yyyy-MM-dd');
      const formattedTime = this.datePipe.transform(date, 'HH:mm');
      return `${formattedDate} \u00B7 ${formattedTime}`;
    } catch (error) {
      console.error("Error parsing date string:", error);
      return dateTimeString;
    }
  }
}

<div class="replyContainer">
    <div class="replyHeader">
        <a [routerLink]="['/profile', localReply.userId]" (click)="$event.stopPropagation()" class="profilePicLink">
            <img class="profilePicture"
                 [src]="getFullImageUrl(localReply.userProfilePicture)"
                 [alt]="'Profile picture of ' + localReply.userNickname">
        </a>
        <div class="userInfoContainer">
            <div class="userInfo">
                <a [routerLink]="['/profile', localReply.userId]" class="nicknameLink" (click)="$event.stopPropagation()">
                    <h3 class="nickname">{{ localReply.userNickname }}</h3>
                </a>
                <p class="time">{{ formatDateTime(localReply.createdAt) }}</p>
            </div>
            <div class="replyContent">
                <p>{{ localReply.content }}</p>
            </div>
        </div>
    </div>

    <div class="actions">
        <div class="interactionButtons">
            <button class="interactionButton likeButton" [class.active]="localReply.liked"
                (click)="handleLikeToggle(); $event.stopPropagation()">
                <img class="interactionIcon" src="/icons/tweet-buttons/like.svg" alt="Like">
                <span class="interactionCount">{{ localReply.likeCount }}</span>
            </button>
            <button class="interactionButton replyButton" (click)="handleReplyClick(); $event.stopPropagation()">
                <img class="interactionIcon" src="/icons/tweet-buttons/reply.svg" alt="Reply">
            </button>
        </div>
        @if (localReply.hasNestedReplies) {
            <button class="toggleNested" (click)="handleToggleNestedClick(); $event.stopPropagation()">
                {{ isNestedVisible ? 'Hide replies' : 'Show replies' }}
            </button>
        }
    </div>
</div>

// frontend-React/src/components/Reply/SingleReply/SingleReply.tsx
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ReplyDetails } from '../../../types/reply/replyDetails';
import { HttpConfig } from '../../../config/http-config';
import styles from './SingleReply.module.css';
import { addLikeToReply, removeLikeFromReply } from '../../../services/replyService';
import { useSelector } from 'react-redux';
import { selectUserId } from '../../../store/slices/authSlice';
import replyIcon from '../../../assets/icons/tweet-buttons/reply.svg';
import likeIcon from '../../../assets/icons/tweet-buttons/like.svg';
import { format, parseISO } from 'date-fns';
import { it } from 'date-fns/locale/it';

interface SingleReplyProps {
  reply: ReplyDetails;
  onOpenReplyPopup: (replyId: number) => void;
  onToggleNested?: (replyId: number) => void;
  isNestedVisible?: boolean;
}

const SingleReply: React.FC<SingleReplyProps> = ({ reply, onOpenReplyPopup, onToggleNested, isNestedVisible }) => {
  const userId = useSelector(selectUserId);
  const [localReply, setLocalReply] = useState<ReplyDetails>(reply);


  useEffect(() => {
    setLocalReply(reply);
  }, [reply]);

  const handleLikeToggle = async (event: React.MouseEvent<HTMLButtonElement>) => {
    event.stopPropagation();
    if (!userId) return;

    const currentLikeId = localReply.likeId;
    const currentlyLiked = localReply.liked;
    const currentLikeCount = localReply.likeCount;

    // Optimistic UI update
    setLocalReply(prev => ({
      ...prev,
      liked: !currentlyLiked,
      likeCount: currentlyLiked ? currentLikeCount - 1 : currentLikeCount + 1,
      likeId: currentlyLiked ? undefined : -1 // Placeholder or temporary ID
    }));

    try {
      if (!currentlyLiked) {
        const likeData = { userId: userId, replyId: localReply.id };
        const result = await addLikeToReply(likeData);
        // Update with actual data from backend
        setLocalReply(prev => ({
          ...prev,
          liked: true,
          likeCount: result.likeCount,
          likeId: result.likeId
        }));
      } else if (currentLikeId) {
        const result = await removeLikeFromReply(currentLikeId);
        // Update with actual data from backend
        setLocalReply(prev => ({
          ...prev,
          liked: false,
          likeCount: result.likeCount,
          likeId: undefined
        }));
      }
    } catch (error) {
      console.error("Failed to toggle like:", error);
      // Revert optimistic update on failure
      setLocalReply(prev => ({ ...prev, liked: currentlyLiked, likeCount: currentLikeCount, likeId: currentLikeId }));
      alert("Could not update like status.");
    }
  };

  const handleReplyClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    event.stopPropagation();
    onOpenReplyPopup(localReply.id);
  }

  const handleToggleNestedClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    event.stopPropagation();
    if (onToggleNested) {
      onToggleNested(localReply.id);
    }
  }

  const getFullImageUrl = (profilePicturePath: string | null | undefined) => {
    if (!profilePicturePath) {
      return '/icons/default-avatar.png';
    }
    return `${HttpConfig.baseUrl}${profilePicturePath}`;
  };

  const formatDateTime = (dateTimeString: string | undefined) => {
    if (!dateTimeString) {
      return '';
    }
    try {
      const date = parseISO(dateTimeString);
      const formattedDate = format(date, 'yyyy-MM-dd', { locale: it });
      const formattedTime = format(date, 'HH:mm', { locale: it });
      return `${formattedDate} \u00B7 ${formattedTime}`;
    } catch (error) {
      console.error("Error parsing date string:", error);
      return dateTimeString;
    }
  };

  return (
    <div className={styles.replyContainer}>
      <div className={styles.replyHeader}>
        <Link
          to={`/profile/${localReply.userId}`}
          onClick={(e) => e.stopPropagation()}
          className={styles.profilePicLink}
        >
          <img
            className={styles.profilePicture}
            src={getFullImageUrl(localReply.userProfilePicture)}
            alt={`Profile picture of ${localReply.userNickname}`}
          />
        </Link>
        <div className={styles.userInfoContainer}>
          <div className={styles.userInfo}>
            <Link
              to={`/profile/${localReply.userId}`}
              className={styles.nicknameLink}
              onClick={(e) => e.stopPropagation()}
            >
              <h3 className={styles.nickname}>{localReply.userNickname}</h3>
            </Link>
            <p className={styles.time}>{formatDateTime(localReply.createdAt)}</p>
          </div>
          <div className={styles.replyContent}>
            <p>{localReply.content}</p>
          </div>
        </div>
      </div>

      <div className={styles.actions}>
        <div className={styles.interactionButtons}>
          <button
            className={`${styles.interactionButton} ${styles.likeButton} ${localReply.liked ? styles.active : ''}`}
            onClick={handleLikeToggle}
          >
            <img className={styles.interactionIcon} src={likeIcon} alt="Like" />
            <span className={styles.interactionCount}>{localReply.likeCount ?? 0}</span>
          </button>
          <button className={`${styles.interactionButton} ${styles.replyButton}`} onClick={handleReplyClick}>
            <img className={styles.interactionIcon} src={replyIcon} alt="Reply" />
          </button>
        </div>
        {localReply.hasNestedReplies && onToggleNested && (
          <button className={styles.toggleNested} onClick={handleToggleNestedClick}>
            {isNestedVisible ? 'Hide replies' : 'Show replies'}
          </button>
        )}
      </div>
    </div>
  );
};

export default SingleReply;
