// frontend-React/src/pages/Bookmarks/Bookmarks.tsx
/* import React, { useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import TweetList from '../../components/Tweet/TweetList/TweetList';
import styles from './Bookmarks.module.css';
import { useSelector } from 'react-redux';
import { selectUserId } from '../../store/slices/authSlice';
import backIcon from '../../assets/icons/back-arrow.svg';

const Bookmarks: React.FC = () => {
  const userId = useSelector(selectUserId);
  const navigate = useNavigate();

  useEffect(() => {
    // Optional: Any specific logic for when the Bookmarks page mounts or userId changes
  }, [userId]);

  const goBack = () => {
    navigate('/home');
  };

  if (!userId) {
    // Handle case where user is not logged in or userId is not available yet
    return (
        <div className={styles.bookmarksContainer}>
            <div className={styles.header}>
                <h1 className={styles.title}>Bookmarks</h1>
            </div>
            <div className={styles.content} style={{ textAlign: 'center', paddingTop: '50px' }}>
                Please log in to see your bookmarks.
            </div>
        </div>
    );
  }

  return (
    <div className={styles.bookmarksContainer}>
        <div className={styles.header}>
          <button onClick={goBack} className={styles.backButton}>
           <img src={backIcon} alt="Go Back" className={styles.arrowIcon} />
           <span className={styles.arrowIcon}></span>
          </button>
            <h1 className={styles.title}>Bookmarks</h1>
        </div>
        <div className={styles.content}>
            <TweetList 
                fetchType='bookmarks'
                userId={userId} 
                listKey={`bookmarks-user-${userId}`}
            />
        </div>
    </div>
  );
};

export default Bookmarks;
 */

import React, { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import TweetList from '../../components/Tweet/TweetList/TweetList';
import styles from './Bookmarks.module.css';
import { useSelector } from 'react-redux';
import { selectUserId } from '../../store/slices/authSlice';
import backIcon from '../../assets/icons/back-arrow.svg';

const Bookmarks: React.FC = () => {
  const userId = useSelector(selectUserId);
  const navigate = useNavigate();

  useEffect(() => {
    // Optional: Any specific logic for when the Bookmarks page mounts or userId changes
  }, [userId]);

  const goBack = () => {
    navigate('/home'); // Or navigate(-1) for a generic back behavior
  };

  // Optional: Handler if Bookmarks.tsx itself needs to react to an unbookmark
  const handleTweetUnbookmarked = (tweetId: number) => {
    console.log(`Tweet ${tweetId} was unbookmarked from the Bookmarks page.`);
    // You could add a toast notification here, for example.
    // The visual removal from the list is handled by TweetList.
  };

  if (!userId) {
    return (
        <div className={styles.bookmarksContainer}>
            <div className={styles.header}>
                {/* It's good practice to have a back button even if not logged in,
                    though its utility might be limited. Or you could hide it. */}
                <button onClick={() => navigate(-1)} className={styles.backButton} aria-label="Go back">
                   <img src={backIcon} alt="Go Back" className={styles.arrowIcon} />
                </button>
                <h1 className={styles.title}>Bookmarks</h1>
            </div>
            <div className={styles.content} style={{ textAlign: 'center', paddingTop: '50px' }}>
                Please log in to see your bookmarks.
            </div>
        </div>
    );
  }

  return (
    <div className={styles.bookmarksContainer}>
        <div className={styles.header}>
          <button onClick={goBack} className={styles.backButton} aria-label="Go back">
           <img src={backIcon} alt="Go Back" className={styles.arrowIcon} />
           {/* The span inside the button was redundant if only using the image, removed it for cleanliness */}
          </button>
            <h1 className={styles.title}>Bookmarks</h1>
        </div>
        <div className={styles.content}>
            <TweetList
                fetchType='bookmarks'
                userId={userId}
                listKey={`bookmarks-user-${userId}`}
                onTweetUnbookmarked={handleTweetUnbookmarked} // Pass the handler
            />
        </div>
    </div>
  );
};

export default Bookmarks;

// frontend/src/app/bookmarks/bookmarks.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Router } from '@angular/router';
import { TweetListComponent } from '../tweet/tweet-list/tweet-list.component';
import { AuthService } from '../model/authentication/authService';
import { CommonModule } from '@angular/common';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

@Component({
  selector: 'app-bookmarks',
  imports: [CommonModule, TweetListComponent],
  templateUrl: './bookmarks.component.html',
  styleUrl: './bookmarks.component.css'
})
export class BookmarksComponent implements OnInit, OnDestroy {
  userId: number | null = null;
  private destroy$ = new Subject<void>();

  constructor(
    private authService: AuthService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.authService.userId$
      .pipe(takeUntil(this.destroy$))
      .subscribe(id => {
        this.userId = id;
      });
  }

  goBack(): void {
    this.router.navigate(['/home']);
  }

  handleTweetUnbookmarked(tweetId: number): void {
    console.log(`Tweet ${tweetId} was unbookmarked from the Bookmarks page.`);
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }
}

<div class="bookmarksContainer">
    <div class="header">
        <button (click)="goBack()" class="backButton" aria-label="Go back">
            <img src="/icons/back-arrow.svg" alt="Go Back" class="arrowIcon" />
        </button>
        <h1 class="title">Bookmarks</h1>
    </div>
    <div class="content">
        @if (userId) {
            <app-tweet-list 
                fetchType='bookmarks'
                [userId]="userId" 
                [listKey]="'bookmarks-user-' + userId"
                (tweetUnbookmarked)="handleTweetUnbookmarked($event)">
            </app-tweet-list>
        } @else {
            <div style="text-align: center; padding-top: 50px;">
                Please log in to see your bookmarks.
            </div>
        }
    </div>
</div>
