// frontend/src/app/authentication/register/register.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { AuthService } from '../../model/authentication/authService';
import { RegisterPayload } from '../../model/authentication/registerDetails';
import { Role } from '../../model/authentication/role';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-register',
  imports: [ReactiveFormsModule, CommonModule],
  templateUrl: './register.component.html',
  styleUrl: './register.component.css'
})
export class RegisterComponent implements OnInit {
  registerForm!: FormGroup;
  selectedFile: File | null = null;
  @Output() closeModal = new EventEmitter<void>();

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.registerForm = this.fb.group({
      firstname: ['', [Validators.required, Validators.minLength(3)]],
      lastname: ['', [Validators.required, Validators.minLength(3)]],
      nickname: ['', [Validators.required, Validators.minLength(3)]],
      dob: ['', Validators.required],
      sex: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(8)]],
      phone: ['', [Validators.required, Validators.minLength(10)]],
      role: ['', Validators.required],
      bio: ['', Validators.maxLength(500)],
      profilePicture: [null] 
    });
  }

  onFileChange(event: Event): void {
    const element = event.currentTarget as HTMLInputElement;
    const fileList: FileList | null = element.files;
    if (fileList && fileList.length > 0) {
      this.selectedFile = fileList[0];
    }
  }

  onSubmit(): void {
    if (this.registerForm.invalid) {
      this.registerForm.markAllAsTouched();
      return;
    }

    const formValues = this.registerForm.value;
    const payload: RegisterPayload = {
        firstname: formValues.firstname,
        lastname: formValues.lastname,
        nickname: formValues.nickname,
        dob: formValues.dob,
        sex: formValues.sex,
        email: formValues.email,
        password: formValues.password,
        phone: formValues.phone,
        role: formValues.role as Role,
        bio: formValues.bio
    };

    let submissionData: RegisterPayload | FormData = payload;

    if (this.selectedFile) {
        const formData = new FormData();
        Object.keys(payload).forEach(key => {
            formData.append(key, (payload as any)[key]);
        });
        formData.append('profilePicture', this.selectedFile, this.selectedFile.name);
        submissionData = formData;
    }

    this.authService.register(submissionData).subscribe({
      next: response => {
        this.authService.setAuth(response.token);
        this.closeModal.emit();
        this.router.navigate(['/home']);
      },
      error: err => {
        console.error('Registration failed:', err);
        alert('Registration failed. Please try again.');
      }
    });
  }
}

<div class="registerContainer">
    <h2>Create your account</h2>
    <form (ngSubmit)="onSubmit()" [formGroup]="registerForm" class="registerForm">
        
        <div class="formGroup">
          <label for="firstname">First Name</label>
          <input type="text" id="firstname" formControlName="firstname" [class.inputError]="registerForm.get('firstname')?.invalid && registerForm.get('firstname')?.touched">
          @if (registerForm.get('firstname')?.invalid && registerForm.get('firstname')?.touched) {
              <span class="validationMessage">
                  @if (registerForm.get('firstname')?.errors?.['required']) {
                      Please enter your first name
                  }
                  @if (registerForm.get('firstname')?.errors?.['minlength']) {
                      At least 3 characters please
                  }
              </span>
          }
        </div>

         <div class="formGroup">
          <label for="lastname">Last Name</label>
          <input type="text" id="lastname" formControlName="lastname" [class.inputError]="registerForm.get('lastname')?.invalid && registerForm.get('lastname')?.touched">
           @if (registerForm.get('lastname')?.invalid && registerForm.get('lastname')?.touched) {
              <span class="validationMessage">
                  @if (registerForm.get('lastname')?.errors?.['required']) {
                       Your last name is important too!
                  }
                  @if (registerForm.get('lastname')?.errors?.['minlength']) {
                      3 characters minimum
                  }
              </span>
          }
        </div>
        
         <div class="formGroup">
          <label for="nickname">Nickname</label>
          <input type="text" id="nickname" formControlName="nickname" [class.inputError]="registerForm.get('nickname')?.invalid && registerForm.get('nickname')?.touched">
          @if (registerForm.get('nickname')?.invalid && registerForm.get('nickname')?.touched) {
              <span class="validationMessage">
                  @if (registerForm.get('nickname')?.errors?.['required']) {
                      How should we call you?
                  }
                  @if (registerForm.get('nickname')?.errors?.['minlength']) {
                      Make it at least 3 characters
                  }
              </span>
          }
        </div>

        <div class="formGroup">
            <label for="dob">Date of Birth</label>
            <input type="date" id="dob" formControlName="dob" [class.inputError]="registerForm.get('dob')?.invalid && registerForm.get('dob')?.touched">
             @if (registerForm.get('dob')?.invalid && registerForm.get('dob')?.touched && registerForm.get('dob')?.errors?.['required']) {
                <span class="validationMessage">We need to know your birthday!</span>
            }
        </div>

        <div class="formGroup">
            <label for="sex">Sex</label>
            <select id="sex" formControlName="sex" [class.inputError]="registerForm.get('sex')?.invalid && registerForm.get('sex')?.touched">
                <option value="">Select...</option>
                <option value="M">Man</option>
                <option value="F">Woman</option>
                <option value="O">Other</option>
            </select>
            @if (registerForm.get('sex')?.invalid && registerForm.get('sex')?.touched && registerForm.get('sex')?.errors?.['required']) {
                <span class="validationMessage">Please select your gender</span>
            }
        </div>

        <div class="formGroup">
          <label for="email">Email</label>
          <input type="email" id="email" formControlName="email" [class.inputError]="registerForm.get('email')?.invalid && registerForm.get('email')?.touched">
          @if (registerForm.get('email')?.invalid && registerForm.get('email')?.touched) {
              <span class="validationMessage">
                  @if (registerForm.get('email')?.errors?.['required']) {
                      Email is required
                  }
                  @if (registerForm.get('email')?.errors?.['email']) {
                      Please enter a valid email
                  }
              </span>
          }
        </div>

         <div class="formGroup">
          <label for="password">Password</label>
          <input type="password" id="password" formControlName="password" [class.inputError]="registerForm.get('password')?.invalid && registerForm.get('password')?.touched">
          @if (registerForm.get('password')?.invalid && registerForm.get('password')?.touched) {
              <span class="validationMessage">
                  @if (registerForm.get('password')?.errors?.['required']) {
                      Password is required
                  }
                  @if (registerForm.get('password')?.errors?.['minlength']) {
                      At least 8 characters please
                  }
              </span>
          }
        </div>

        <div class="formGroup">
            <label for="phone">Phone</label>
            <input type="tel" id="phone" formControlName="phone" [class.inputError]="registerForm.get('phone')?.invalid && registerForm.get('phone')?.touched">
            @if (registerForm.get('phone')?.invalid && registerForm.get('phone')?.touched) {
              <span class="validationMessage">
                  @if (registerForm.get('phone')?.errors?.['required']) {
                      Phone number is required
                  }
                  @if (registerForm.get('phone')?.errors?.['minlength']) {
                      At least 10 digits please
                  }
              </span>
          }
        </div>

        <div class="formGroup">
            <label for="role">Role</label>
            <select id="role" formControlName="role" [class.inputError]="registerForm.get('role')?.invalid && registerForm.get('role')?.touched">
                <option value="">Select...</option>
                <option value="ADMIN">Admin</option>
                <option value="USER">User</option>
                <option value="MANAGER">Manager</option>
            </select>
            @if (registerForm.get('role')?.invalid && registerForm.get('role')?.touched && registerForm.get('role')?.errors?.['required']) {
                <span class="validationMessage">Please select a role</span>
            }
        </div>

         <div class="formGroup">
            <label for="profilePicture">Profile Image (Optional)</label>
            <input type="file" id="profilePicture" accept=".jpg, .jpeg, .png" (change)="onFileChange($event)" class="fileInput">
        </div>

         <div class="formGroup">
          <label for="bio">Bio (Optional)</label>
          <textarea id="bio" formControlName="bio" rows="5" placeholder="Tell us a bit about yourself..." [class.inputError]="registerForm.get('bio')?.invalid && registerForm.get('bio')?.touched"></textarea>
          @if (registerForm.get('bio')?.invalid && registerForm.get('bio')?.touched && registerForm.get('bio')?.errors?.['maxlength']) {
            <span class="validationMessage">Bio cannot exceed 500 characters</span>
          }
        </div>

        <button type="submit" [disabled]="!registerForm.valid" class="submitBtn">
          Register
        </button>
    </form>
</div>

// frontend-React/src/components/Authentication/Register/Register.tsx
import React from 'react';
import { useForm, SubmitHandler, Controller } from 'react-hook-form';
import { register as registerUser } from '../../../services/authService';
import { RegisterFormData, RegisterPayload } from '../../../types/authentication/registerDetails';
import { Role } from '../../../types/authentication/role';
import styles from './Register.module.css';
import { useDispatch } from 'react-redux';
import { setAuth } from '../../../store/slices/authSlice';
import { AppDispatch } from '../../../store/store';

interface RegisterProps {
    onClose: () => void;
}

const Register: React.FC<RegisterProps> = ({ onClose }) => {
  const dispatch = useDispatch<AppDispatch>();
  const { register, handleSubmit, control, formState: { errors, isValid } } = useForm<RegisterFormData>({
      mode: 'onBlur', 
      defaultValues: {
          firstname: '',
          lastname: '',
          nickname: '',
          dob: '',
          sex: '',
          email: '',
          password: '',
          phone: '',
          role: '',
          profilePicture: null,
          bio: ''
      }
  });

  const onSubmit: SubmitHandler<RegisterFormData> = async (data) => {
    if (!data.role) {
        console.error('Role is required');
        
        return;
    }

    const payload: RegisterPayload = {
        firstname: data.firstname,
        lastname: data.lastname,
        nickname: data.nickname,
        dob: data.dob,
        sex: data.sex,
        email: data.email,
        password: data.password,
        phone: data.phone,
        role: data.role,
        bio: data.bio        
    };

    
    let submissionData: RegisterPayload | FormData = payload;

    if (data.profilePicture) {
        const formData = new FormData();
        Object.keys(payload).forEach(key => {
             
             
             
             if (key !== 'profilePicture') {
                formData.append(key, (payload as any)[key] as string);
            }
        });
        formData.append('profilePicture', data.profilePicture);
        submissionData = formData;
    }

    try {
      const response = await registerUser(submissionData);
      dispatch(setAuth({ token: response.token })); 
      onClose(); 
      
    } catch (error) { 
      console.error('Registration failed:', error);
      alert('Registration failed. Please try again.'); 
    }
  };

  return (
    <div className={styles.registerContainer}>
      <h2>Create your account</h2>
      <form onSubmit={handleSubmit(onSubmit)} className={styles.registerForm}>
        
        <div className={styles.formGroup}>
          <label htmlFor="firstname">First Name</label>
          <input
            type="text"
            id="firstname"
            {...register('firstname', { required: 'Please enter your first name', minLength: { value: 3, message: 'At least 3 characters please' } })}
            className={errors.firstname ? styles.inputError : ''}
          />
          {errors.firstname && <span className={styles.validationMessage}>{errors.firstname.message}</span>}
        </div>

        
         <div className={styles.formGroup}>
          <label htmlFor="lastname">Last Name</label>
          <input
            type="text"
            id="lastname"
            {...register('lastname', { required: 'Your last name is important too!', minLength: { value: 3, message: '3 characters minimum' } })}
            className={errors.lastname ? styles.inputError : ''}
          />
          {errors.lastname && <span className={styles.validationMessage}>{errors.lastname.message}</span>}
        </div>

        
         <div className={styles.formGroup}>
          <label htmlFor="nickname">Nickname</label>
          <input
            type="text"
            id="nickname"
            {...register('nickname', { required: 'How should we call you?', minLength: { value: 3, message: 'Make it at least 3 characters' } })}
            className={errors.nickname ? styles.inputError : ''}
          />
          {errors.nickname && <span className={styles.validationMessage}>{errors.nickname.message}</span>}
        </div>

        
        <div className={styles.formGroup}>
            <label htmlFor="dob">Date of Birth</label>
            <input 
                type="date" 
                id="dob" 
                {...register('dob', { required: 'We need to know your birthday!' })} 
                className={errors.dob ? styles.inputError : ''}
            />
            {errors.dob && <span className={styles.validationMessage}>{errors.dob.message}</span>}
        </div>

        
        <div className={styles.formGroup}>
            <label htmlFor="sex">Sex</label>
            <select 
                id="sex" 
                {...register('sex', { required: 'Please select your gender' })} 
                className={errors.sex ? styles.inputError : ''}
            >
                <option value="">Select...</option>
                <option value="M">Man</option>
                <option value="F">Woman</option>
                <option value="O">Other</option>
            </select>
            {errors.sex && <span className={styles.validationMessage}>{errors.sex.message}</span>}
        </div>

        
        <div className={styles.formGroup}>
          <label htmlFor="email">Email</label>
          <input
            type="email"
            id="email"
            {...register('email', { required: 'Email is required', pattern: { value: /^\S+@\S+$/i, message: 'Please enter a valid email' } })}
            className={errors.email ? styles.inputError : ''}
          />
          {errors.email && <span className={styles.validationMessage}>{errors.email.message}</span>}
        </div>

        
         <div className={styles.formGroup}>
          <label htmlFor="password">Password</label>
          <input
            type="password"
            id="password"
            {...register('password', { required: 'Password is required', minLength: { value: 8, message: 'At least 8 characters please' } })}
            className={errors.password ? styles.inputError : ''}
          />
          {errors.password && <span className={styles.validationMessage}>{errors.password.message}</span>}
        </div>

        
        <div className={styles.formGroup}>
            <label htmlFor="phone">Phone</label>
            <input 
                type="tel" 
                id="phone" 
                {...register('phone', { required: 'Phone number is required', minLength: { value: 10, message: 'At least 10 digits please' } })} 
                className={errors.phone ? styles.inputError : ''}
            />
            {errors.phone && <span className={styles.validationMessage}>{errors.phone.message}</span>}
        </div>

        
        <div className={styles.formGroup}>
            <label htmlFor="role">Role</label>
            <select 
                id="role" 
                {...register('role', { required: 'Please select a role' })} 
                className={errors.role ? styles.inputError : ''}
            >
                <option value="">Select...</option>
                <option value={Role.ADMIN}>Admin</option>
                <option value={Role.USER}>User</option>
                <option value={Role.MANAGER}>Manager</option>
            </select>
            {errors.role && <span className={styles.validationMessage}>{errors.role.message}</span>}
        </div>

        
         <div className={styles.formGroup}>
            <label htmlFor="profilePicture">Profile Image (Optional)</label>
            <Controller
                name="profilePicture"
                control={control}
                render={({ field: { onChange, onBlur, name, ref } }) => (
                    <input 
                        type="file" 
                        id="profilePicture"
                        accept=".jpg, .jpeg, .png"
                        onChange={(e) => onChange(e.target.files ? e.target.files[0] : null)}
                        onBlur={onBlur}
                        name={name}
                        ref={ref}
                        className={styles.fileInput} 
                    />
                )}
             />
        </div>

        
         <div className={styles.formGroup}>
          <label htmlFor="bio">Bio (Optional)</label>
          <textarea
            id="bio"
            {...register('bio', { maxLength: 500 })}
            rows={5}
             placeholder="Tell us a bit about yourself..."
             className={errors.bio ? styles.inputError : ''}
          />
          {errors.bio && <span className={styles.validationMessage}>{errors.bio.message}</span>}
        </div>

        <button type="submit" disabled={!isValid} className={styles.submitBtn}>
          Register
        </button>
      </form>
    </div>
  );
};

export default Register;
